export type Language = 'ENGLISH' | 'SINHALA' | 'TAMIL';

const english: Record<string, string> = {
  // ── App core ──────────────────────────────────────────────
  appTitle: 'MyTax',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax Digital Solutions (Pvt) Ltd',
  welcome: 'Welcome to MyTax !',
  selectBeforeNext: 'Select Before Next',
  language: 'Language',
  respondIn: 'Respond in',
  text: 'TEXT',
  voice: 'VOICE',
  next: 'NEXT',
  declaration: 'Declaration',
  declarationBody:
    'The company will be used your financial information for tax submission only. Further the service provider is not responsible for any of false or manipulated information if it\'s given by your applicants. The storage to the documents will be performed with user applicant permission. And we are not responsible for the legal implications for your tax matters.',

  // ── User Verification ─────────────────────────────────────
  userVerification: 'User Verification',
  nicNumber: 'NIC Number:',
  mobileNumber: 'Mobile Number:',
  underNic: '[Under your NIC]',
  note: '* Note',
  noteBody:
    '1. The Registered mobile number should be used for the access. Further the system will require your identity confirmation from relevant department for protection to control the misuse of our services.',
  sendOtp: 'Send OTP to verify Now',
  enterOtp: 'Enter the OTP sent to your mobile',
  verifyOtp: 'Verify OTP',
  resendOtp: 'Resend OTP',
  verifiedMessage:
    'The user has been verified successfully. You can login now!',
  login: 'Login',
  fillAllFields: 'Please fill in all fields',
  enterCompleteOtp: 'Please enter the complete OTP',

  // ── Login Screen ──────────────────────────────────────────
  loginTitle: 'Login',
  password: 'Password:',
  usePasskey: 'Use Pass key',
  registerNew: 'Register New',
  forgotPassword: 'Forgot Password?',
  loginFillFields: 'Please enter NIC and Password',

  // ── Register Screen ───────────────────────────────────────
  registerTitle: 'Register New!',
  fullName: 'Full Name: *',
  mobileNo: 'Mobile No: *',
  emailAddress: 'Email Address: *',
  markLocation: 'Mark your location: *',
  clickToMark: '-Click to mark location-',
  district: 'District:*',
  dsDivision: 'DS Division:*',
  gsDivision: 'GS Division:*',
  postalAddress: 'Postal Address:',
  postalNo: ': No',
  addLine: ': Add Line',
  createPassword: 'Create Password: *',
  usePasskeyBiometric: 'Use Passkey/ Biometric Access',
  verifyAndCreate: 'Verify & Create',
  registerFillFields: 'Please fill all required fields',

  // ── Dashboard ─────────────────────────────────────────────
  welcomeMyTax: 'Welcome to MyTax !',
  thankYouReg: 'Thank you registering with MyTax Services!',
  happySupport:
    'We are happy to support to complete your tax responsibility for the Country Development.',
  registeredClient: 'You have been registered as a tax client.',
  clientCode: 'Client Code:',
  clientName: 'Client Name:',
  tinNumber: 'TIN Number:',
  contactNo: 'Contact No:',
  mailAddress: 'Mail Address:',
  myTaxServices: 'My Tax Services',
  guide: 'Guide',
  logout: 'Logout',

  // ── Tax Services ──────────────────────────────────────────
  taxServicesTitle: 'MyTax Services',
  primaryService: 'Primary Service',
  supportService: 'Support Service',
  m1: 'M1 - Tax File Submission',
  m2: 'M2 - TIN Number Status (Free)',
  m3: 'M3 - Tax Calculator (Free)',
  m5: 'M5 - Final Tax Computation (Paid)',
  m6: 'M6 - TIN Certificate Request (Paid)',
  m7: 'M7 - TIN Certificate Application (Paid)',
  m8: 'M8 - Tax Payer Information Update (Paid)',
  m9: 'M9 - Tax Administration Support (Paid)',

  // ── Guide ─────────────────────────────────────────────────
  guideTitle: 'User General Guide',
  userGuideSection: 'User Guide',
  documentsForLogin: 'Documents need to Create Login',
  taxGeneralGuide: 'Tax General Guide',
  taxFillingImportance: 'Tax Filling Importance!',
  taxFilingTypes: 'Tax Filing Types!',
  taxPayerRegDocs: 'Tax Payer Registration Required Documents!',
  taxFilingPenalty: 'Tax Filing Avoidance Penalty!',
  taxFilingReqDocs: 'Tax Filing Required Documents!',
  taxInfoUpdateDocs: 'Tax Payer Information Update Required Documents!',
  skip: 'Skip',

  // ── Website-specific ──────────────────────────────────────
  heroTagline: 'Sri Lanka\'s trusted digital tax filing platform',
  getStarted: 'Get Started',
  learnMore: 'Learn More',
  signIn: 'Sign In',
  services: 'Services',
  aboutUs: 'About Us',
  home: 'Home',
  footerTagline: 'Complete tax filing and TIN management solutions for Sri Lankan taxpayers.',
  quickLinks: 'Quick Links',
  legal: 'Legal',
  contact: 'Contact',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  faq: 'FAQ',
  aboutTitle: 'About MyTax',
  aboutDesc: 'MyTax is a comprehensive digital platform by Matrix Investments PLC, designed to simplify tax filing and compliance for Sri Lankan taxpayers.',
  secureTitle: 'Secure & Reliable',
  secureDesc: 'Your financial data is protected with enterprise-grade security. We follow strict data protection protocols.',
  fastTitle: 'Fast & Efficient',
  fastDesc: 'Complete your tax filings in minutes from anywhere. No paperwork, no queues — fully digital.',
  supportTitle: 'Expert Support',
  supportDesc: 'Our team of tax professionals is ready to guide you through every step of your tax journey.',

  // ── Navigation additions ──────────────────────────────────
  about: 'About',
  groupCompanies: 'Group Companies',
  investorRelations: 'Investor Relations',
  careers: 'Careers',
  contactComplaints: 'Contact & Complaints',
  legalPrivacy: 'Legal & Privacy',
  more: 'More',

  // ── Verify page additions ─────────────────────────────────
  phoneTab: 'Phone Number',
  emailTab: 'Email',
  verifyViaPhone: 'Verify via Phone OTP',
  verifyViaEmail: 'Verify via Email OTP',
  emailInput: 'Email Address:',

  // ── About page ────────────────────────────────────────────
  aboutPageTitle: 'About Matrix Investments PLC',
  aboutPageDesc: 'Building Sri Lanka\'s most trusted digital tax infrastructure through innovation, integrity, and inclusion.',
  aboutPageMission: 'Our Mission',
  aboutPageMissionDesc: 'To provide every Sri Lankan taxpayer with accessible, accurate, and affordable digital tax services — simplifying compliance and eliminating the burden of manual filing through technology.',
  aboutPageVision: 'Our Vision',
  aboutPageVisionDesc: 'To become South Asia\'s leading digital tax compliance platform, empowering 2 million+ taxpayers with AI-driven guidance and integrated government API access by 2030.',
  aboutMatrixDesc1: 'Matrix Investments PLC is a Sri Lankan holding company focused on financial technology, tax services, and business consulting. Established to bridge the gap between Sri Lankan taxpayers and the Inland Revenue Department, we provide end-to-end solutions from TIN registration to annual tax filing.',
  aboutMatrixDesc2: 'Our group of companies operates across digital platforms, national tax booths, financial advisory, and compliance management — ensuring every segment of the population has access to professional tax support, whether digital or assisted.',

  // ── Group Companies page ──────────────────────────────────
  groupPageTitle: 'Our Group Companies',
  groupPageDesc: 'Matrix Investments PLC operates through six specialized subsidiaries, each focused on a distinct aspect of tax, finance, and technology services in Sri Lanka.',

  // ── Investor Relations page ───────────────────────────────
  investorPageTitle: 'Investor Relations',
  investorPageDesc: 'Matrix Investments PLC is committed to transparency, sustainable growth, and delivering value to all stakeholders. We welcome strategic investors aligned with our mission of digital tax transformation in Sri Lanka.',
  whyInvest: 'Why Invest in Matrix',
  investorContact: 'For investor enquiries, contact us at investors@matrix.lk',

  // ── Careers page ──────────────────────────────────────────
  careersPageTitle: 'Careers at Matrix',
  careersPageDesc: 'Join Sri Lanka\'s fastest-growing digital tax platform. We\'re looking for passionate individuals to help transform the way millions of Sri Lankans manage their taxes.',
  openPositions: 'Open Positions',
  applyNow: 'Apply Now',
  noOpenings: 'No current openings. Check back soon or send your CV to careers@matrix.lk',
  whyUs: 'Why Work With Us',

  // ── Contact & Complaints page ─────────────────────────────
  contactPageTitle: 'Contact & Complaints',
  contactPageDesc: 'We value your feedback and are committed to resolving any concerns promptly. Reach out through any channel below.',
  contactFormName: 'Full Name',
  contactFormEmail: 'Email Address',
  contactFormPhone: 'Phone Number',
  contactFormSubject: 'Subject',
  contactFormMessage: 'Your Message',
  submitBtn: 'Submit',
  complaintSection: 'File a Complaint',
  getInTouch: 'Get in Touch',
  thankYouContact: 'Thank you! We\'ll respond within 24 hours.',

  // ── Legal & Privacy page ──────────────────────────────────
  legalPageTitle: 'Legal & Privacy',
  legalPageDesc: 'Matrix Investments PLC is committed to protecting your personal data in compliance with the Personal Data Protection Act (PDPA) of Sri Lanka.',
  pdpaTitle: 'PDPA Compliance',
  pdpaDesc: 'We are fully compliant with the Personal Data Protection Act No. 9 of 2022 (Sri Lanka). Your data is collected only with your explicit consent and used solely for the purposes you have agreed to.',
  privacyPolicyFull: 'Privacy Policy',
  termsOfServiceFull: 'Terms of Service',
  dataProtection: 'Data Protection',
  consentFramework: 'Consent Framework',
  dataRetention: 'Data Retention',
  yourRights: 'Your Rights',

  // ── Services page ─────────────────────────────────────────
  servicesPageTitle: 'Our Services',
  servicesPageDesc: 'Comprehensive tax and financial services for individuals and businesses across Sri Lanka.',
  individualTaxFiling: 'Individual Tax Filing',
  individualTaxDesc: 'Complete income tax return filing for employed individuals, self-employed persons, and professionals. We handle everything from document collection to IRD submission.',
  businessTaxFiling: 'Business Tax Filing',
  businessTaxDesc: 'Corporate income tax and VAT return preparation and filing for businesses of all sizes — from sole proprietorships to listed companies.',
  tinRegistration: 'TIN Registration',
  tinRegistrationDesc: 'Taxpayer Identification Number (TIN) application and registration service. We guide you through the entire process with the Inland Revenue Department.',
  complianceMonitoring: 'Compliance Monitoring',
  complianceMonitoringDesc: 'Continuous monitoring of your tax obligations, due dates, penalty flags, and risk indicators to ensure you stay compliant year-round.',

  // ── Guide page ────────────────────────────────────────────
  guidePageTitle: 'Guide & Resources',
  guidePageDesc: 'Free educational resources to help you understand your tax obligations and use our platform effectively.',
  guideUseOfTaxServices: 'Use Of Tax Services',
  guideUserGuide: 'User Guide',
  guideAgentGuide: 'Agent Guide',
  guideAboutUs: 'About Us',
  guideHelpAI: 'Help AI Instructor',
  guideTaxCalendar: 'Tax Calendar',
  freeOfCharge: 'Free of Charge',
  watchNow: 'Watch Now',
  comingSoon: 'Coming Soon',
};

const sinhala: Record<string, string> = {
  appTitle: 'මයිටැක්ස්',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax ඩිජිටල් විසඳුම් (Pvt) Ltd',
  welcome: 'MyTax වෙත සාදරයෙන් පිළිගනිමු !',
  selectBeforeNext: 'ඊළඟට යාමට පෙර තෝරන්න',
  language: 'භාෂාව',
  respondIn: 'පිළිතුරු ආකාරය',
  text: 'පෙළ',
  voice: 'හඬ',
  next: 'ඊළඟ',
  declaration: 'ප්‍රකාශය',
  declarationBody:
    'සමාගම ඔබේ මූල්‍ය තොරතුරු බදු ඉදිරිපත් කිරීම සඳහා පමණක් භාවිතා කරනු ඇත. සේවා සපයන්නා ව්‍යාජ තොරතුරු සඳහා වගකිව යුතු නොවේ. ලේඛන ගබඩා කිරීම පරිශීලකයාගේ අනුමැතිය ඇතිව සිදු කෙරේ. ඔබේ බදු කටයුතු සම්බන්ධ නෛතික ප්‍රතිවිපාක සඳහා අපි වගකිව යුතු නොවේ.',
  userVerification: 'පරිශීලක සත්‍යාපනය',
  nicNumber: 'NIC අංකය:',
  mobileNumber: 'ජංගම අංකය:',
  underNic: '[ඔබේ NIC යටතේ]',
  note: '* සටහන',
  noteBody:
    '1. ලියාපදිංචි ජංගම අංකය ප්‍රවේශය සඳහා භාවිතා කළ යුතුය. තවද පද්ධතිය ඔබේ අනන්‍යතා තහවුරු කිරීම අවශ්‍ය වනු ඇත.',
  sendOtp: 'OTP යවා දැන් සත්‍යාපනය කරන්න',
  enterOtp: 'ඔබේ ජංගමයට යවන ලද OTP ඇතුළත් කරන්න',
  verifyOtp: 'OTP සත්‍යාපනය කරන්න',
  resendOtp: 'OTP නැවත යවන්න',
  verifiedMessage: 'පරිශීලකයා සාර්ථකව සත්‍යාපනය කරන ලදී. දැන් පුරනය වන්න!',
  login: 'පුරනය වන්න',
  fillAllFields: 'සියලු ක්ෂේත්‍ර පුරවන්න',
  enterCompleteOtp: 'සම්පූර්ණ OTP ඇතුළත් කරන්න',
  loginTitle: 'පුරනය වන්න',
  password: 'මුරපදය:',
  usePasskey: 'පාස්කී භාවිතා කරන්න',
  registerNew: 'නව ලියාපදිංචිය',
  forgotPassword: 'මුරපදය අමතකද?',
  loginFillFields: 'NIC සහ මුරපදය ඇතුළත් කරන්න',
  registerTitle: 'නව ලියාපදිංචිය!',
  fullName: 'සම්පූර්ණ නම: *',
  mobileNo: 'ජංගම අංකය: *',
  emailAddress: 'විද්‍යුත් තැපෑල: *',
  markLocation: 'ස්ථානය සලකුණු කරන්න: *',
  clickToMark: '-ස්ථානය සලකුණු කිරීමට ක්ලික් කරන්න-',
  district: 'දිස්ත්‍රික්කය:*',
  dsDivision: 'DS කොට්ඨාශය:*',
  gsDivision: 'GS කොට්ඨාශය:*',
  postalAddress: 'තැපැල් ලිපිනය:',
  postalNo: ': අංකය',
  addLine: ': රේඛාව එකතු කරන්න',
  createPassword: 'මුරපදය සාදන්න: *',
  usePasskeyBiometric: 'පාස්කී / ජෛව මිතික ප්‍රවේශය',
  verifyAndCreate: 'සත්‍යාපනය කර සාදන්න',
  registerFillFields: 'සියලු අවශ්‍ය ක්ෂේත්‍ර පුරවන්න',
  welcomeMyTax: 'MyTax වෙත සාදරයෙන් පිළිගනිමු !',
  thankYouReg: 'MyTax සේවා සඳහා ලියාපදිංචි වීමට ස්තූතියි!',
  happySupport:
    'රටේ සංවර්ධනය සඳහා ඔබේ බදු වගකීම සම්පූර්ණ කිරීමට සහාය වීමට අපි සතුටු වෙමු.',
  registeredClient: 'ඔබ බදු සේවාදායකයෙකු ලෙස ලියාපදිංචි වී ඇත.',
  clientCode: 'සේවාදායක කේතය:',
  clientName: 'සේවාදායක නම:',
  tinNumber: 'TIN අංකය:',
  contactNo: 'සම්බන්ධතා අංකය:',
  mailAddress: 'විද්‍යුත් ලිපිනය:',
  myTaxServices: 'මගේ බදු සේවා',
  guide: 'මාර්ගෝපදේශය',
  logout: 'පිටවීම',
  taxServicesTitle: 'MyTax සේවා',
  primaryService: 'ප්‍රාථමික සේවාව',
  supportService: 'සහාය සේවාව',
  m1: 'M1 - බදු ගොනු ඉදිරිපත් කිරීම',
  m2: 'M2 - TIN අංක තත්ත්වය (නිෂ්ශ්‍රේණිය)',
  m3: 'M3 - බදු කැල්කියුලේටරය (නිෂ්ශ්‍රේණිය)',
  m5: 'M5 - අවසාන බදු ගණනය (ගෙවිය යුතු)',
  m6: 'M6 - TIN සහතික ඉල්ලීම (ගෙවිය යුතු)',
  m7: 'M7 - TIN සහතික අයදුම්පත (ගෙවිය යුතු)',
  m8: 'M8 - බදු ගෙවන්නාගේ තොරතුරු යාවත්කාලීන (ගෙවිය යුතු)',
  m9: 'M9 - බදු පරිපාලන සහාය (ගෙවිය යුතු)',
  guideTitle: 'පොදු මාර්ගෝපදේශය',
  userGuideSection: 'පරිශීලක මාර්ගෝපදේශය',
  documentsForLogin: 'පුරනය සෑදීමට අවශ්‍ය ලේඛන',
  taxGeneralGuide: 'බදු පොදු මාර්ගෝපදේශය',
  taxFillingImportance: 'බදු ඉදිරිපත් කිරීමේ වැදගත්කම!',
  taxFilingTypes: 'බදු ඉදිරිපත් කිරීමේ වර්ග!',
  taxPayerRegDocs: 'බදු ගෙවන්නා ලියාපදිංචිය ලේඛන!',
  taxFilingPenalty: 'බදු ඉදිරිපත් නොකිරීමේ දඩ!',
  taxFilingReqDocs: 'බදු ඉදිරිපත් කිරීමට අවශ්‍ය ලේඛන!',
  taxInfoUpdateDocs: 'බදු ගෙවන්නාගේ තොරතුරු යාවත්කාලීන ලේඛන!',
  skip: 'මඟ හරින්න',
  heroTagline: 'ශ්‍රී ලංකාවේ විශ්වාසදායක ඩිජිටල් බදු ගෙවීමේ වේදිකාව',
  getStarted: 'ආරම්භ කරන්න',
  learnMore: 'තව දැනගන්න',
  signIn: 'පුරනය',
  services: 'සේවා',
  aboutUs: 'අප ගැන',
  home: 'මුල් පිටුව',
  footerTagline: 'ශ්‍රී ලාංකික බදු ගෙවන්නන් සඳහා සම්පූර්ණ බදු ගොනු කිරීමේ සහ TIN කළමනාකරණ විසඳුම්.',
  quickLinks: 'ශීඝ්‍ර සබැඳි',
  legal: 'නෛතික',
  contact: 'සම්බන්ධතා',
  privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය',
  termsOfService: 'සේවා නියම',
  faq: 'නිතර අසන ප්‍රශ්න',
  aboutTitle: 'MyTax ගැන',
  aboutDesc: 'MyTax යනු Matrix Investments PLC විසින් ශ්‍රී ලාංකික බදු ගෙවන්නන් සඳහා බදු ගොනු කිරීම සහ අනුකූලතාව සරල කිරීමට නිර්මාණය කරන ලද ඩිජිටල් වේදිකාවකි.',
  secureTitle: 'ආරක්ෂිත සහ විශ්වාසදායක',
  secureDesc: 'ඔබේ මූල්‍ය දත්ත ව්‍යවසාය මට්ටමේ ආරක්ෂාවෙන් ආරක්ෂා වේ.',
  fastTitle: 'වේගවත් සහ කාර්යක්ෂම',
  fastDesc: 'ඕනෑම තැනක සිට විනාඩි කිහිපයකින් බදු ගොනු සම්පූර්ණ කරන්න.',
  supportTitle: 'විශේෂඥ සහාය',
  supportDesc: 'අපගේ බදු විශේෂඥ කණ්ඩායම ඔබේ බදු ගමනේ සෑම පියවරකටම සහාය දක්විනු ඇත.',

  about: 'ගැන',
  groupCompanies: 'සමූහ සමාගම්',
  investorRelations: 'ආයෝජක සබඳතා',
  careers: 'රැකියා',
  contactComplaints: 'සම්බන්ධතා & පැමිණිලි',
  legalPrivacy: 'නෛතික & රහස්‍යතාව',
  more: 'තව',
  phoneTab: 'දුරකථන අංකය',
  emailTab: 'විද්‍යුත් තැපෑල',
  verifyViaPhone: 'දුරකථනය හරහා OTP සත්‍යාපනය',
  verifyViaEmail: 'විද්‍යුත් තැපෑල හරහා OTP සත්‍යාපනය',
  emailInput: 'විද්‍යුත් තැපෑල:',
  aboutPageTitle: 'Matrix Investments PLC ගැන',
  aboutPageDesc: 'නව්‍යකරණය, අඛණ්ඩතාව සහ ඇතුළත් කිරීම හරහා ශ්‍රී ලංකාවේ වඩාත්ම විශ්වාසදායක ඩිජිටල් බදු යටිතල ගොඩනැඟීම.',
  aboutPageMission: 'අපගේ මෙහෙවෙර',
  aboutPageMissionDesc: 'ශ්‍රී ලාංකික සෑම බදු ගෙවන්නෙකුටම ගැළෙනසුළු, නිවැරදි සහ දැරිය හැකි ඩිජිටල් බදු සේවා සැපයීම — තාක්ෂණය හරහා ශ්‍රමසාධ්‍ය ලේඛනකරණය ඉවත් කිරීම.',
  aboutPageVision: 'අපගේ දර්ශනය',
  aboutPageVisionDesc: '2030 වන විට AI-추진 මාර්ගෝපදේශය සහිතව ලක්ෂ 20+ ක් බදු ගෙවන්නන්ට සහාය වීමට දකුණු ආසියාවේ ප්‍රමුඛ ඩිජිටල් බදු වේදිකාව බවට පත් වීම.',
  aboutMatrixDesc1: 'Matrix Investments PLC යනු ශ්‍රී ලාංකික බදු ගෙවන්නන් සහ ආදායම් දෙපාර්තමේන්තුව අතර පරතරය පිරවීමට ස්ථාපිත, TIN ලියාපදිංචියේ සිට වාර්ෂික බදු ගොනු කිරීම දක්වා විසඳුම් සපයන මූල්‍ය තාක්ෂණ ශ්‍රී ලාංකික රක්ෂාකාරී සමාගමකි.',
  aboutMatrixDesc2: 'අපගේ සමාගම් කණ්ඩායම ඩිජිටල් වේදිකා, ජාතික බදු ඇතිකළු, මූල්‍ය උපදේශන සහ අනුකූලතා කළමනාකරණය හරහා ක්‍රියාත්මක වේ.',
  groupPageTitle: 'අපගේ සමූහ සමාගම්',
  groupPageDesc: 'Matrix Investments PLC ශ්‍රී ලංකාවේ බදු, මූල්‍ය සහ තාක්ෂණ සේවා කෙරෙහි අවධානය යොමු කළ විශේෂිත අනුෂ්ඨාන හයක් (6) හරහා ක්‍රියාත්මක වේ.',
  investorPageTitle: 'ආයෝජක සබඳතා',
  investorPageDesc: 'Matrix Investments PLC විනිවිදභාවය, තිරස්ථාරී වර්ධනය සහ සියලු ස්‍ථාවරකරුවන්ට වටිනාකම ලබා දීමට කැපවී සිටී.',
  whyInvest: 'Matrix හි ආයෝජනය කළ යුත්තේ ඇයි',
  investorContact: 'ආයෝජක ගැටළු සඳහා: investors@matrix.lk',
  careersPageTitle: 'Matrix හි රැකියා',
  careersPageDesc: 'ශ්‍රී ලංකාවේ වේගයෙන් වර්ධනය වන ඩිජිටල් බදු වේදිකාවට සම්බන්ධ වන්න.',
  openPositions: 'ලබා ගත හැකි රැකියා',
  applyNow: 'දැන් ඉල්ලුම් කරන්න',
  noOpenings: 'දැනට ලබා ගත හැකි රැකියා නොමැත. careers@matrix.lk හෝ ඔබේ CV යවන්න.',
  whyUs: 'අප සමඟ ක්‍රියා කළ යුත්තේ ඇයි',
  contactPageTitle: 'සම්බන්ධතා & පැමිණිලි',
  contactPageDesc: 'ඔබේ ප්‍රතිපෝෂණය අප තකා ගනිමු. ඕනෑම නාලිකාවක් හරහා අප වෙත ළඟා වෙන්න.',
  contactFormName: 'සම්පූර්ණ නම',
  contactFormEmail: 'විද්‍යුත් තැපෑල',
  contactFormPhone: 'දුරකතන අංකය',
  contactFormSubject: 'විෂය',
  contactFormMessage: 'ඔබේ පණිවිඩය',
  submitBtn: 'ඉදිරිපත් කරන්න',
  complaintSection: 'පැමිණිල්ලක් ඉදිරිපත් කරන්න',
  getInTouch: 'සම්බන්ධ වෙන්න',
  thankYouContact: 'ස්තූතියි! අපි පැය 24 ක් ඇතුළත ප්‍රතිචාර දක්වන්නෙමු.',
  legalPageTitle: 'නෛතික & රහස්‍යතාව',
  legalPageDesc: 'Matrix Investments PLC ශ්‍රී ලංකාවේ PDPA ට අනුකූලව ඔබේ පෞද්ගලික දත්ත ආරක්ෂා කිරීමට කැපවී සිටී.',
  pdpaTitle: 'PDPA අනුකූලතාව',
  pdpaDesc: 'ශ්‍රී ලංකා පෞද්ගලික දත්ත ආරක්ෂණ පනතට (2022) යටත්ව, ඔබේ දත්ත ඔබේ සෘජු (explicit) කැමැත්ත ඇතිව පමණක් රැස් කෙරේ.',
  privacyPolicyFull: 'රහස්‍යතා ප්‍රතිපත්තිය',
  termsOfServiceFull: 'සේවා නියම',
  dataProtection: 'දත්ත ආරක්ෂාව',
  consentFramework: 'කැමැත්ත රාමුව',
  dataRetention: 'දත්ත රඳවා ගැනීම',
  yourRights: 'ඔබේ අයිතිවාසිකම්',
  servicesPageTitle: 'අපගේ සේවාවන්',
  servicesPageDesc: 'ශ්‍රී ලංකාව පුරා පුද්ගලයන් සහ ව්‍යාපාරයන් සඳහා සම්පූර්ණ බදු සහ මූල්‍ය සේවාවන්.',
  individualTaxFiling: 'තනි පුද්ගල බදු ගොනු කිරීම',
  individualTaxDesc: 'රැකියා ලාභීන්, ස්වයං රැකියා සහ වෘත්තිකයන් සඳහා සම්පූර්ණ ආදායම් බදු ගොනු කිරීම.',
  businessTaxFiling: 'ව්‍යාපාරික බදු ගොනු කිරීම',
  businessTaxDesc: 'සෑම ප්‍රමාණයකම ව්‍යාපාරයන් සඳහා ආයතනික ආදායම් බදු සහ VAT ගොනු කිරීම.',
  tinRegistration: 'TIN ලියාපදිංචිය',
  tinRegistrationDesc: 'TIN ඉල්ලුම් සහ ලියාපදිංචිය. ආදායම් දෙපාර්තමේන්තුව සමඟ සම්පූර්ණ ක්‍රියාවලිය.',
  complianceMonitoring: 'අනුකූලතා නිරීක්ෂණය',
  complianceMonitoringDesc: 'ඔබේ බදු බාධ්‍යතාවන්, නිවසේ දිනයන්, දඩ ලකුණු සහ අවදානම් දර්ශක නිරන්තර නිරීක්ෂණය.',
  guidePageTitle: 'මාර්ගෝපදේශ සහ සම්පත්',
  guidePageDesc: 'ඔබේ බදු බාධ්‍යතාව තේරුම් ගැනීමට සහ අපගේ වේදිකාව effectively භාවිතා කිරීමට නිෂ්ශ්‍රේණිය ශික්ෂණ සම්පත්.',
  guideUseOfTaxServices: 'බදු සේවා භාවිතය',
  guideUserGuide: 'පරිශීලක මාර්ගෝපදේශය',
  guideAgentGuide: 'නියෝජිත මාර්ගෝපදේශය',
  guideAboutUs: 'අප ගැන',
  guideHelpAI: 'AI සහාය උපදේශකය',
  guideTaxCalendar: 'බදු දිනදර්ශනය',
  freeOfCharge: 'නිෂ්ශ්‍රේණිය',
  watchNow: 'දැන් නරඹන්න',
  comingSoon: 'ළඟදීම',
};

const tamil: Record<string, string> = {
  appTitle: 'மைடாக்ஸ்',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax டிஜிட்டல் தீர்வுகள் (Pvt) Ltd',
  welcome: 'மைடாக்ஸ் க்கு வரவேற்கிறோம் !',
  selectBeforeNext: 'அடுத்ததற்கு முன் தேர்வு செய்யவும்',
  language: 'மொழி',
  respondIn: 'பதில் வகை',
  text: 'உரை',
  voice: 'குரல்',
  next: 'அடுத்து',
  declaration: 'அறிவிப்பு',
  declarationBody:
    'இந்த நிறுவனம் உங்கள் நிதி தகவல்களை வரி தாக்கல் மட்டுமே பயன்படுத்தும். சேவை வழங்குநர் பொய்யான அல்லது திருத்தப்பட்ட தகவல்களுக்கு பொறுப்பல்ல. ஆவணங்கள் சேமிப்பு பயனரின் அனுமதியோடு மேற்கொள்ளப்படும். உங்கள் வரி விவகாரங்களுக்கான சட்ட விளைவுகளுக்கு நாங்கள் பொறுப்பல்ல.',
  userVerification: 'பயனர் சரிபார்ப்பு',
  nicNumber: 'NIC எண்:',
  mobileNumber: 'மொபைல் எண்:',
  underNic: '[உங்கள் NIC கீழ்]',
  note: '* குறிப்பு',
  noteBody:
    '1. பதிவு செய்யப்பட்ட மொபைல் எண் அணுகலுக்கு பயன்படுத்தப்பட வேண்டும். மேலும் அமைப்பு உங்கள் அடையாள உறுதிப்படுத்தல் தேவைப்படும்.',
  sendOtp: 'OTP அனுப்பி சரிபார்க்கவும்',
  enterOtp: 'உங்கள் மொபைலுக்கு அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்',
  verifyOtp: 'OTP சரிபார்க்கவும்',
  resendOtp: 'OTP மீண்டும் அனுப்பவும்',
  verifiedMessage:
    'பயனர் வெற்றிகரமாக சரிபார்க்கப்பட்டார். இப்போது உள்நுழையலாம்!',
  login: 'உள்நுழைவு',
  fillAllFields: 'அனைத்து புலங்களையும் நிரப்பவும்',
  enterCompleteOtp: 'முழுமையான OTP ஐ உள்ளிடவும்',
  loginTitle: 'உள்நுழைவு',
  password: 'கடவுச்சொல்:',
  usePasskey: 'பாஸ்கீ பயன்படுத்து',
  registerNew: 'புதிதாக பதிவு செய்',
  forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
  loginFillFields: 'NIC மற்றும் கடவுச்சொல் உள்ளிடவும்',
  registerTitle: 'புதிதாக பதிவு செய்யுங்கள்!',
  fullName: 'முழு பெயர்: *',
  mobileNo: 'மொபைல் எண்: *',
  emailAddress: 'மின்னஞ்சல்: *',
  markLocation: 'இடத்தை குறிக்கவும்: *',
  clickToMark: '-இடத்தை குறிக்க கிளிக் செய்யவும்-',
  district: 'மாவட்டம்:*',
  dsDivision: 'DS பிரிவு:*',
  gsDivision: 'GS பிரிவு:*',
  postalAddress: 'தபால் முகவரி:',
  postalNo: ': எண்',
  addLine: ': வரி சேர்',
  createPassword: 'கடவுச்சொல் உருவாக்கு: *',
  usePasskeyBiometric: 'பாஸ்கீ / உயிரியல் அணுகல்',
  verifyAndCreate: 'சரிபார்த்து உருவாக்கு',
  registerFillFields: 'அனைத்து கட்டாயமான புலங்களையும் நிரப்பவும்',
  welcomeMyTax: 'MyTax க்கு வரவேற்கிறோம் !',
  thankYouReg: 'MyTax சேவைகளில் பதிவு செய்தமைக்கு நன்றி!',
  happySupport:
    'நாட்டின் வளர்ச்சிக்கான உங்கள் வரி பொறுப்பை நிறைவேற்ற உதவுவதில் மகிழ்ச்சி.',
  registeredClient:
    'நீங்கள் வரி வாடிக்கையாளராக பதிவு செய்யப்பட்டுள்ளீர்கள்.',
  clientCode: 'வாடிக்கையாளர் குறியீடு:',
  clientName: 'வாடிக்கையாளர் பெயர்:',
  tinNumber: 'TIN எண்:',
  contactNo: 'தொடர்பு எண்:',
  mailAddress: 'மின்னஞ்சல்:',
  myTaxServices: 'என் வரி சேவைகள்',
  guide: 'வழிகாட்டி',
  logout: 'வெளியேறு',
  taxServicesTitle: 'MyTax சேவைகள்',
  primaryService: 'முதன்மை சேவை',
  supportService: 'ஆதரவு சேவை',
  m1: 'M1 - வரி கோப்பு சமர்ப்பணம்',
  m2: 'M2 - TIN எண் நிலை (இலவசம்)',
  m3: 'M3 - வரி கணக்கீட்டி (இலவசம்)',
  m5: 'M5 - இறுதி வரி கணக்கீடு (கட்டண)',
  m6: 'M6 - TIN சான்றிதழ் கோரிக்கை (கட்டண)',
  m7: 'M7 - TIN சான்றிதழ் விண்ணப்பம் (கட்டண)',
  m8: 'M8 - வரி செலுத்துவோர் தகவல் புதுப்பிப்பு (கட்டண)',
  m9: 'M9 - வரி நிர்வாக ஆதரவு (கட்டண)',
  guideTitle: 'பொது வழிகாட்டி',
  userGuideSection: 'பயனர் வழிகாட்டி',
  documentsForLogin: 'உள்நுழைவு உருவாக்க தேவையான ஆவணங்கள்',
  taxGeneralGuide: 'வரி பொது வழிகாட்டி',
  taxFillingImportance: 'வரி தாக்கல் முக்கியத்துவம்!',
  taxFilingTypes: 'வரி தாக்கல் வகைகள்!',
  taxPayerRegDocs: 'வரி செலுத்துவோர் பதிவு ஆவணங்கள்!',
  taxFilingPenalty: 'வரி தவிர்ப்பு அபராதம்!',
  taxFilingReqDocs: 'வரி தாக்கல் தேவையான ஆவணங்கள்!',
  taxInfoUpdateDocs: 'வரி செலுத்துவோர் தகவல் புதுப்பிப்பு ஆவணங்கள்!',
  skip: 'தவிர்',
  heroTagline: 'இலங்கையின் நம்பகமான டிஜிட்டல் வரி தாக்கல் தளம்',
  getStarted: 'தொடங்குங்கள்',
  learnMore: 'மேலும் அறிக',
  signIn: 'உள்நுழைவு',
  services: 'சேவைகள்',
  aboutUs: 'எங்களை பற்றி',
  home: 'முகப்பு',
  footerTagline: 'இலங்கை வரி செலுத்துவோருக்கான முழுமையான வரி தாக்கல் மற்றும் TIN மேலாண்மை தீர்வுகள்.',
  quickLinks: 'விரைவு இணைப்புகள்',
  legal: 'சட்ட',
  contact: 'தொடர்பு',
  privacyPolicy: 'தனியுரிமைக் கொள்கை',
  termsOfService: 'சேவை விதிமுறைகள்',
  faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
  aboutTitle: 'MyTax பற்றி',
  aboutDesc: 'MyTax என்பது Matrix Investments PLC ஆல் இலங்கை வரி செலுத்துவோருக்கான டிஜிட்டல் தளமாகும்.',
  secureTitle: 'பாதுகாப்பான & நம்பகமான',
  secureDesc: 'உங்கள் நிதி தரவு நிறுவன தர பாதுகாப்புடன் பாதுகாக்கப்படுகிறது.',
  fastTitle: 'வேகமான & திறமையான',
  fastDesc: 'எங்கிருந்தும் சில நிமிடங்களில் வரி தாக்கல்களை முடிக்கவும்.',
  supportTitle: 'நிபுணர் ஆதரவு',
  supportDesc: 'எங்கள் வரி நிபுணர்கள் உங்கள் வரி பயணத்தின் ஒவ்வொரு படிக்கும் வழிகாட்டுவார்கள்.',

  about: 'பற்றி',
  groupCompanies: 'குழு நிறுவனங்கள்',
  investorRelations: 'முதலீட்டாளர் தொடர்பு',
  careers: 'வாழ்க்கை வாய்ப்புகள்',
  contactComplaints: 'தொடர்பு & புகார்கள்',
  legalPrivacy: 'சட்ட & தனியுரிமை',
  more: 'மேலும்',
  phoneTab: 'தொலைபேசி எண்',
  emailTab: 'மின்னஞ்சல்',
  verifyViaPhone: 'தொலைபேசி OTP மூலம் சரிபார்க்கவும்',
  verifyViaEmail: 'மின்னஞ்சல் OTP மூலம் சரிபார்க்கவும்',
  emailInput: 'மின்னஞ்சல் முகவரி:',
  aboutPageTitle: 'Matrix Investments PLC பற்றி',
  aboutPageDesc: 'நவீனம், நேர்மை மற்றும் உள்ளடக்கம் மூலம் இலங்கையின் மிகவும் நம்பகமான டிஜிட்டல் வரி உள்கட்டமைப்பை உருவாக்குதல்.',
  aboutPageMission: 'எங்கள் நோக்கம்',
  aboutPageMissionDesc: 'ஒவ்வொரு இலங்கை வரி செலுத்துவோருக்கும் அணுகக்கூடிய, துல்லியமான மற்றும் மலிவான டிஜிட்டல் வரி சேவைகளை வழங்குதல் — தொழில்நுட்பம் மூலம் கைமுறை தாக்கல் சுமையை நீக்குதல்.',
  aboutPageVision: 'எங்கள் பார்வை',
  aboutPageVisionDesc: '2030ல் AI வழிகாட்டல் மற்றும் ஒருங்கிணைந்த அரசு API அணுகல் மூலம் 20 லட்சத்திற்கும் மேலான வரி செலுத்துவோரை வலுப்படுத்தி தென் ஆசியாவின் முன்னணி டிஜிட்டல் வரி தளமாக மாறுதல்.',
  aboutMatrixDesc1: 'Matrix Investments PLC என்பது இலங்கை வரி செலுத்துவோருக்கும் உள்நாட்டு வருவாய் திணைக்களத்திற்கும் இடையிலான இடைவெளியை நிரப்ப நிறுவப்பட்ட நிதித் தொழில்நுட்ப நிறுவனம்.',
  aboutMatrixDesc2: 'எங்கள் குழு டிஜிட்டல் தளங்கள், தேசிய வரி கண்டிகள், நிதி ஆலோசனை மற்றும் இணக்க மேலாண்மை வழியாக செயல்படுகிறது.',
  groupPageTitle: 'எங்கள் குழு நிறுவனங்கள்',
  groupPageDesc: 'Matrix Investments PLC இலங்கையில் வரி, நிதி மற்றும் தொழில்நுட்ப சேவைகளில் தேர்ச்சி பெற்ற ஆறு சிறப்பு துணை நிறுவனங்கள் மூலம் செயல்படுகிறது.',
  investorPageTitle: 'முதலீட்டாளர் தொடர்பு',
  investorPageDesc: 'Matrix Investments PLC வெளிப்படைத்தன்மை, நிலையான வளர்ச்சி மற்றும் அனைத்து பங்குதாரர்களுக்கும் மதிப்பை வழங்குவதில் கடமைப்பட்டுள்ளது.',
  whyInvest: 'Matrix இல் முதலீடு ஏன்',
  investorContact: 'முதலீட்டாளர் விசாரணைகளுக்கு: investors@matrix.lk',
  careersPageTitle: 'Matrix இல் வாழ்க்கை வாய்ப்புகள்',
  careersPageDesc: 'இலங்கையின் வேகமாக வளரும் டிஜிட்டல் வரி தளத்தில் சேரவும். மில்லியன் கணக்கான இலங்கையர்களின் வரி மேலாண்மையை மாற்ற உதவ ஆர்வமுள்ளவர்களை தேடுகிறோம்.',
  openPositions: 'தற்போதைய வாய்ப்புகள்',
  applyNow: 'இப்போது விண்ணப்பிக்கவும்',
  noOpenings: 'தற்போது வாய்ப்புகள் இல்லை. careers@matrix.lk க்கு CV அனுப்பவும்.',
  whyUs: 'எங்களுடன் ஏன் பணிபுரிவது',
  contactPageTitle: 'தொடர்பு & புகார்கள்',
  contactPageDesc: 'உங்கள் கருத்தை நாங்கள் மதிக்கிறோம். கீழேயுள்ள எந்த சேனல் மூலமும் தொடர்புகொள்ளுங்கள்.',
  contactFormName: 'முழு பெயர்',
  contactFormEmail: 'மின்னஞ்சல்',
  contactFormPhone: 'தொலைபேசி எண்',
  contactFormSubject: 'விஷயம்',
  contactFormMessage: 'உங்கள் செய்தி',
  submitBtn: 'சமர்பிக்கவும்',
  complaintSection: 'புகார் தாக்கல் செய்யுங்கள்',
  getInTouch: 'தொடர்பு கொள்ளுங்கள்',
  thankYouContact: 'நன்றி! 24 மணி நேரத்தில் பதிலளிப்போம்.',
  legalPageTitle: 'சட்ட & தனியுரிமை',
  legalPageDesc: 'Matrix Investments PLC இலங்கை PDPA க்கு இணங்க உங்கள் தனிப்பட்ட தரவை பாதுகாக்க கடமைப்பட்டுள்ளது.',
  pdpaTitle: 'PDPA இணக்கம்',
  pdpaDesc: 'இலங்கை தனிப்பட்ட தரவு பாதுகாப்பு சட்டம் எண். 9 (2022) க்கு ஏற்ப, உங்கள் தரவு உங்கள் வெளிப்படையான ஒப்புதலுடன் மட்டுமே சேகரிக்கப்படுகிறது.',
  privacyPolicyFull: 'தனியுரிமைக் கொள்கை',
  termsOfServiceFull: 'சேவை விதிமுறைகள்',
  dataProtection: 'தரவு பாதுகாப்பு',
  consentFramework: 'ஒப்புதல் கட்டமைப்பு',
  dataRetention: 'தரவு தேக்கம்',
  yourRights: 'உங்கள் உரிமைகள்',
  servicesPageTitle: 'எங்கள் சேவைகள்',
  servicesPageDesc: 'இலங்கை முழுவதும் தனிநபர்கள் மற்றும் வணிகங்களுக்கான விரிவான வரி மற்றும் நிதி சேவைகள்.',
  individualTaxFiling: 'தனிப்பட்ட வரி தாக்கல்',
  individualTaxDesc: 'வேலைசெய்பவர்கள், சுயதொழில் மற்றும் தொழில் வல்லுநர்களுக்கான வருமான வரி தாக்கல்.',
  businessTaxFiling: 'வணிக வரி தாக்கல்',
  businessTaxDesc: 'அனைத்து அளவு வணிகங்களுக்கான நிறுவன வருமான வரி மற்றும் VAT தாக்கல்.',
  tinRegistration: 'TIN பதிவு',
  tinRegistrationDesc: 'TIN விண்ணப்பம் மற்றும் பதிவு சேவை. உள்நாட்டு வருவாய் திணைக்களத்துடன் முழு செயல்முறை வழிகாட்டல்.',
  complianceMonitoring: 'இணக்க கண்காணிப்பு',
  complianceMonitoringDesc: 'உங்கள் வரி கடமைகள், தவணை தேதிகள், அபராத குறிகள் மற்றும் ஆபத்து குறிகாட்டிகளை தொடர்ச்சியான கண்காணிப்பு.',
  guidePageTitle: 'வழிகாட்டி & வளங்கள்',
  guidePageDesc: 'உங்கள் வரி கடமைகளை புரிந்துகொள்ள மற்றும் தளத்தை பயனுள்ள முறையில் பயன்படுத்த இலவச கல்வி வளங்கள்.',
  guideUseOfTaxServices: 'வரி சேவைகளின் பயன்பாடு',
  guideUserGuide: 'பயனர் வழிகாட்டி',
  guideAgentGuide: 'ஏஜெண்ட் வழிகாட்டி',
  guideAboutUs: 'எங்களை பற்றி',
  guideHelpAI: 'AI உதவி பயிற்றுவிப்பாளர்',
  guideTaxCalendar: 'வரி நாட்காட்டி',
  freeOfCharge: 'இலவசம்',
  watchNow: 'இப்போது பாருங்கள்',
  comingSoon: 'விரைவில்',
};

export function getStrings(language: Language): Record<string, string> {
  switch (language) {
    case 'TAMIL':
      return tamil;
    case 'SINHALA':
      return sinhala;
    default:
      return english;
  }
}
