export type Language = 'ENGLISH' | 'SINHALA' | 'TAMIL';

const english: Record<string, string> = {
  // ── App core ──────────────────────────────────────────────
  appTitle: 'MyTax',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax Digital Solutions (Pvt) Ltd',
  welcome: 'Welcome to MyTax !',
  selectBeforeNext: 'Select Before Next',
  language: 'Language',
  respondIn: 'Respond in',
  text: 'TEXT',
  voice: 'VOICE',
  next: 'NEXT',
  declaration: 'Declaration',
  declarationBody:
    'The company will be used your financial information for tax submission only. Further the service provider is not responsible for any of false or manipulated information if it\'s given by your applicants. The storage to the documents will be performed with user applicant permission. And we are not responsible for the legal implications for your tax matters.',

  // ── User Verification ─────────────────────────────────────
  userVerification: 'User Verification',
  nicNumber: 'NIC Number:',
  mobileNumber: 'Mobile Number:',
  underNic: '[Under your NIC]',
  note: '* Note',
  noteBody:
    '1. The Registered mobile number should be used for the access. Further the system will require your identity confirmation from relevant department for protection to control the misuse of our services.',
  sendOtp: 'Send OTP to verify Now',
  enterOtp: 'Enter the OTP sent to your mobile',
  verifyOtp: 'Verify OTP',
  resendOtp: 'Resend OTP',
  verifiedMessage:
    'The user has been verified successfully. You can login now!',
  login: 'Login',
  fillAllFields: 'Please fill in all fields',
  enterCompleteOtp: 'Please enter the complete OTP',

  // ── Login Screen ──────────────────────────────────────────
  loginTitle: 'Login',
  password: 'Password:',
  usePasskey: 'Use Pass key',
  registerNew: 'Register New',
  forgotPassword: 'Forgot Password?',
  loginFillFields: 'Please enter NIC and Password',

  // ── Register Screen ───────────────────────────────────────
  registerTitle: 'Register New!',
  fullName: 'Full Name: *',
  mobileNo: 'Mobile No: *',
  emailAddress: 'Email Address: *',
  markLocation: 'Mark your location: *',
  clickToMark: '-Click to mark location-',
  district: 'District:*',
  dsDivision: 'DS Division:*',
  gsDivision: 'GS Division:*',
  postalAddress: 'Postal Address:',
  postalNo: ': No',
  addLine: ': Add Line',
  createPassword: 'Create Password: *',
  usePasskeyBiometric: 'Use Passkey/ Biometric Access',
  verifyAndCreate: 'Verify & Create',
  registerFillFields: 'Please fill all required fields',

  // ── Dashboard ─────────────────────────────────────────────
  welcomeMyTax: 'Welcome to MyTax !',
  thankYouReg: 'Thank you registering with MyTax Services!',
  happySupport:
    'We are happy to support to complete your tax responsibility for the Country Development.',
  registeredClient: 'You have been registered as a tax client.',
  clientCode: 'Client Code:',
  clientName: 'Client Name:',
  tinNumber: 'TIN Number:',
  contactNo: 'Contact No:',
  mailAddress: 'Mail Address:',
  myTaxServices: 'My Tax Services',
  guide: 'Guide',
  logout: 'Logout',

  // ── Tax Services ──────────────────────────────────────────
  taxServicesTitle: 'MyTax Services',
  primaryService: 'Primary Service',
  supportService: 'Support Service',
  m1: 'M1 - Tax File Submission',
  m2: 'M2 - TIN Number Status (Free)',
  m3: 'M3 - Tax Calculator (Free)',
  m5: 'M5 - Final Tax Computation (Paid)',
  m6: 'M6 - TIN Certificate Request (Paid)',
  m7: 'M7 - TIN Certificate Application (Paid)',
  m8: 'M8 - Tax Payer Information Update (Paid)',
  m9: 'M9 - Tax Administration Support (Paid)',

  // ── Guide ─────────────────────────────────────────────────
  guideTitle: 'User General Guide',
  userGuideSection: 'User Guide',
  documentsForLogin: 'Documents need to Create Login',
  taxGeneralGuide: 'Tax General Guide',
  taxFillingImportance: 'Tax Filling Importance!',
  taxFilingTypes: 'Tax Filing Types!',
  taxPayerRegDocs: 'Tax Payer Registration Required Documents!',
  taxFilingPenalty: 'Tax Filing Avoidance Penalty!',
  taxFilingReqDocs: 'Tax Filing Required Documents!',
  taxInfoUpdateDocs: 'Tax Payer Information Update Required Documents!',
  skip: 'Skip',

  // ── Website-specific ──────────────────────────────────────
  heroTagline: 'Sri Lanka\'s trusted digital tax filing platform',
  getStarted: 'Get Started',
  learnMore: 'Learn More',
  signIn: 'Sign In',
  services: 'Services',
  aboutUs: 'About Us',
  home: 'Home',
  footerTagline: 'Complete tax filing and TIN management solutions for Sri Lankan taxpayers.',
  quickLinks: 'Quick Links',
  legal: 'Legal',
  contact: 'Contact',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  faq: 'FAQ',
  aboutTitle: 'About MyTax',
  aboutDesc: 'MyTax is a comprehensive digital platform by Matrix Investments PLC, designed to simplify tax filing and compliance for Sri Lankan taxpayers.',
  secureTitle: 'Secure & Reliable',
  secureDesc: 'Your financial data is protected with enterprise-grade security. We follow strict data protection protocols.',
  fastTitle: 'Fast & Efficient',
  fastDesc: 'Complete your tax filings in minutes from anywhere. No paperwork, no queues — fully digital.',
  supportTitle: 'Expert Support',
  supportDesc: 'Our team of tax professionals is ready to guide you through every step of your tax journey.',

  // ── Navigation additions ──────────────────────────────────
  about: 'About',
  groupCompanies: 'Group Companies',
  investorRelations: 'Investor Relations',
  careers: 'Careers',
  contactComplaints: 'Contact & Complaints',
  legalPrivacy: 'Legal & Privacy',
  more: 'More',

  // ── Verify page additions ─────────────────────────────────
  phoneTab: 'Phone Number',
  emailTab: 'Email',
  verifyViaPhone: 'Verify via Phone OTP',
  verifyViaEmail: 'Verify via Email OTP',
  emailInput: 'Email Address:',

  // ── About page ────────────────────────────────────────────
  aboutPageTitle: 'About Matrix Investments PLC',
  aboutPageDesc: 'Building Sri Lanka\'s most trusted digital tax infrastructure through innovation, integrity, and inclusion.',
  aboutPageMission: 'Our Mission',
  aboutPageMissionDesc: 'To provide every Sri Lankan taxpayer with accessible, accurate, and affordable digital tax services — simplifying compliance and eliminating the burden of manual filing through technology.',
  aboutPageVision: 'Our Vision',
  aboutPageVisionDesc: 'To become South Asia\'s leading digital tax compliance platform, empowering 2 million+ taxpayers with AI-driven guidance and integrated government API access by 2030.',
  aboutMatrixDesc1: 'Matrix Investments PLC is a Sri Lankan holding company focused on financial technology, tax services, and business consulting. Established to bridge the gap between Sri Lankan taxpayers and the Inland Revenue Department, we provide end-to-end solutions from TIN registration to annual tax filing.',
  aboutMatrixDesc2: 'Our group of companies operates across digital platforms, national tax booths, financial advisory, and compliance management — ensuring every segment of the population has access to professional tax support, whether digital or assisted.',

  // ── Group Companies page ──────────────────────────────────
  groupPageTitle: 'Our Group Companies',
  groupPageDesc: 'Matrix Investments PLC operates through six specialized subsidiaries, each focused on a distinct aspect of tax, finance, and technology services in Sri Lanka.',

  // ── Investor Relations page ───────────────────────────────
  investorPageTitle: 'Investor Relations',
  investorPageDesc: 'Matrix Investments PLC is committed to transparency, sustainable growth, and delivering value to all stakeholders. We welcome strategic investors aligned with our mission of digital tax transformation in Sri Lanka.',
  whyInvest: 'Why Invest in Matrix',
  investorContact: 'For investor enquiries, contact us at investors@matrix.lk',

  // ── Careers page ──────────────────────────────────────────
  careersPageTitle: 'Careers at Matrix',
  careersPageDesc: 'Join Sri Lanka\'s fastest-growing digital tax platform. We\'re looking for passionate individuals to help transform the way millions of Sri Lankans manage their taxes.',
  openPositions: 'Open Positions',
  applyNow: 'Apply Now',
  noOpenings: 'No current openings. Check back soon or send your CV to careers@matrix.lk',
  whyUs: 'Why Work With Us',

  // ── Contact & Complaints page ─────────────────────────────
  contactPageTitle: 'Contact & Complaints',
  contactPageDesc: 'We value your feedback and are committed to resolving any concerns promptly. Reach out through any channel below.',
  contactFormName: 'Full Name',
  contactFormEmail: 'Email Address',
  contactFormPhone: 'Phone Number',
  contactFormSubject: 'Subject',
  contactFormMessage: 'Your Message',
  submitBtn: 'Submit',
  complaintSection: 'File a Complaint',
  getInTouch: 'Get in Touch',
  thankYouContact: 'Thank you! We\'ll respond within 24 hours.',

  // ── Legal & Privacy page ──────────────────────────────────
  legalPageTitle: 'Legal & Privacy',
  legalPageDesc: 'Matrix Investments PLC is committed to protecting your personal data in compliance with the Personal Data Protection Act (PDPA) of Sri Lanka.',
  pdpaTitle: 'PDPA Compliance',
  pdpaDesc: 'We are fully compliant with the Personal Data Protection Act No. 9 of 2022 (Sri Lanka). Your data is collected only with your explicit consent and used solely for the purposes you have agreed to.',
  privacyPolicyFull: 'Privacy Policy',
  termsOfServiceFull: 'Terms of Service',
  dataProtection: 'Data Protection',
  consentFramework: 'Consent Framework',
  dataRetention: 'Data Retention',
  yourRights: 'Your Rights',

  // ── Services page ─────────────────────────────────────────
  servicesPageTitle: 'Our Services',
  servicesPageDesc: 'Comprehensive tax and financial services for individuals and businesses across Sri Lanka.',
  individualTaxFiling: 'Individual Tax Filing',
  individualTaxDesc: 'Complete income tax return filing for employed individuals, self-employed persons, and professionals. We handle everything from document collection to IRD submission.',
  businessTaxFiling: 'Business Tax Filing',
  businessTaxDesc: 'Corporate income tax and VAT return preparation and filing for businesses of all sizes — from sole proprietorships to listed companies.',
  tinRegistration: 'TIN Registration',
  tinRegistrationDesc: 'Taxpayer Identification Number (TIN) application and registration service. We guide you through the entire process with the Inland Revenue Department.',
  complianceMonitoring: 'Compliance Monitoring',
  complianceMonitoringDesc: 'Continuous monitoring of your tax obligations, due dates, penalty flags, and risk indicators to ensure you stay compliant year-round.',

  // ── Guide page ────────────────────────────────────────────
  guidePageTitle: 'Guide & Resources',
  guidePageDesc: 'Free educational resources to help you understand your tax obligations and use our platform effectively.',
  guideUseOfTaxServices: 'Use Of Tax Services',
  guideUserGuide: 'User Guide',
  guideAgentGuide: 'Agent Guide',
  guideAboutUs: 'About Us',
  guideHelpAI: 'Help AI Instructor',
  guideTaxCalendar: 'Tax Calendar',
  freeOfCharge: 'Free of Charge',
  watchNow: 'Watch Now',
  comingSoon: 'Coming Soon',

  // ── General UI ────────────────────────────────────────────
  paid: 'Paid',
  free: 'Free',
  guideNote: 'Full guide content coming soon',
  subsidiaryServices: 'Subsidiary Services',
  groupStructure: 'Group Structure',
  groupStructureNote: 'All subsidiaries operate under the strategic direction of Matrix Investments PLC, with shared governance, compliance standards, and technology infrastructure.',
  partnerWithUs: 'Partner With Us',
  partnerWithUsDesc: 'We welcome strategic investors, institutional partners, and government collaborators aligned with our mission of digital tax transformation.',
  dontSeeRole: "Don't See Your Role?",
  dontSeeRoleDesc: "Send your CV and portfolio to our HR team. We're always looking for talented individuals passionate about tax technology.",
  sendAnother: 'Send Another',
  sending: 'Sending...',
  reviewAndRespond: 'Our team will review your message and respond shortly.',
  taxFilingComplianceTitle: 'Tax Filing & Compliance',
  myTaxDigitalServices: 'MyTax Digital Services',
  readyToFile: 'Ready to File Your Taxes?',
  readyToFileDesc: 'Create your account in minutes and let our platform handle your tax compliance.',
  investmentCase: 'Investment Case',
  cultureBenefits: 'Culture & Benefits',
  currentOpenings: 'Current Openings',
  coreServices: 'Core Services',
  platformModules: 'Platform Modules',
  videoGuidesTitle: 'Tax Simple Guidance Videos',
  smsAlertsTitle: 'SMS Alert Notifications',
  smsAlertsDesc: 'Stay informed with automatic SMS notifications for every step of your tax journey:',
  businessModelTitle: 'Business Model Overview',

  // ── About page stats ─────────────────────────────────────
  statsClients: 'Clients Served',
  statsYears: 'Years Experience',
  statsTaxReturns: 'Tax Returns Filed',
  statsDistricts: 'Districts Covered',

  // ── S&C service categories ────────────────────────────────
  scAccounts: 'Accounts',
  scProposals: 'Proposals',
  scInventory: 'Inventory Management',
  scTaxCategory: 'Tax',
  scCompanyReg: 'Company Registrations',
  scSecretarial: 'Company Secretarial Works',
  scRealEstate: 'Real Estates',
  scMonthlyFinance: 'Monthly Finance Monitoring',
  scMonthlyAccounts: 'Monthly Accounts',
  scProfitReports: 'Business Profit Reports',
  scLoanAccounts: 'Loan Purpose Accounts',
  scAnnualAccounts: 'Annual Accounts',
  scLoanProposal: 'Loan Proposal',
  scBusinessProposal: 'Business Proposal',
  scStockVerification: 'Stock Verification',
  scDigitalStock: 'Digital Bar Stock Counts',
  scIncomeTaxFiling: 'Income Tax Filing',
  scIncomeTaxReg: 'Income Tax Registration',
  scVatConsult: 'VAT Consultations',
  scTaxConsult: 'Tax Consultations',
  scBusinessReg: 'Business Registration',
  scCharityReg: 'Charity Registration',
  scAnnualReturn: 'Annual Return Filing',
  scSecretary: 'Secretary Services',
  scDealAdvisory: 'Deal Advisory',

  // ── Digital tools ─────────────────────────────────────────
  toolMyTaxApp: 'MyTax Digital App',
  toolGuidanceVideos: 'Tax Simple Guidance Videos',
  toolUserGuideLabel: 'User Guide',
  toolAIInstructor: 'AI Tax Instructor',
  toolTaxCalendar: 'Tax Calendar',
  toolAgentGuide: 'Agent Guide',

  // ── Group Companies ───────────────────────────────────────
  company1Tagline: 'Business & Tax Consulting Excellence',
  company1Desc: 'Providing comprehensive accounting, tax, company registration, secretarial and real estate advisory services to businesses and individuals across Sri Lanka.',
  company2Tagline: 'Digital Tax Innovation',
  company2Desc: 'The technology arm of Matrix Investments PLC, driving the MyTax digital platform for tax filing and compliance management.',
  company3Tagline: 'Nationwide Tax Access Points',
  company3Desc: 'Manages the Matrix Tax Booth national rollout providing assisted TIN registration, app onboarding, and voice-based tax filing services across GS Divisions.',
  company4Tagline: 'Investment & Finance Advisory',
  company4Desc: 'Providing expert financial advisory, investment planning, and capital management services to corporate and individual clients.',
  company5Tagline: 'Regulatory Compliance Management',
  company5Desc: 'Specialized in regulatory compliance monitoring, audit trail management, and government liaison services.',
  company6Tagline: 'Data Intelligence for Tax',
  company6Desc: 'Driving data analytics and intelligence solutions supporting client database management and AI-based tax questionnaire systems.',
  svcAccounts: 'Accounts',
  svcTaxFiling: 'Tax Filing',
  svcCompanyReg: 'Company Registrations',
  svcInventoryMgmt: 'Inventory Management',
  svcRealEstate: 'Real Estates',
  svcProposals: 'Proposals',
  svcSecretarialWorks: 'Secretarial Works',
  svcMyTaxApp: 'MyTax App',
  svcDigitalTaxFiling: 'Digital Tax Filing',
  svcTINServices: 'TIN Services',
  svcComplianceTools: 'Compliance Tools',
  svcAIAssistant: 'AI Tax Assistant',
  svcTINRegistration: 'TIN Registration',
  svcAppOnboarding: 'App Onboarding',
  svcVoiceFiling: 'Voice Filing',
  svcPaymentGuidance: 'Payment Guidance',
  svcFinancialAdvisory: 'Financial Advisory',
  svcInvestmentPlanning: 'Investment Planning',
  svcCapitalManagement: 'Capital Management',
  svcRiskAssessment: 'Risk Assessment',
  svcComplianceAudits: 'Compliance Audits',
  svcRiskManagement: 'Risk Management',
  svcGovernmentLiaison: 'Government Liaison',
  svcRegulatoryReporting: 'Regulatory Reporting',
  svcDataAnalytics: 'Data Analytics',
  svcClientDatabase: 'Client Database Management',
  svcReportingTools: 'Reporting Tools',

  // ── Investor Relations ────────────────────────────────────
  whyGrowingMarket: 'Growing Market',
  whyGrowingMarketDesc: 'Sri Lanka has 10+ million taxable individuals. Less than 30% currently file returns, representing a massive growth opportunity.',
  whyRegulatoryTailwind: 'Regulatory Tailwind',
  whyRegulatoryTailwindDesc: 'Government mandates for digital tax submission and TIN registration are driving rapid adoption of digital platforms.',
  whyTechMoat: 'Technology Moat',
  whyTechMoatDesc: 'Proprietary AI tax questionnaire, multilingual voice interface, and GS Division booth network create strong competitive barriers.',
  whyGovPartnership: 'Government Partnership',
  whyGovPartnershipDesc: 'Strategic partnership with IRD for data access APIs and national tax booth rollout creates a defensible market position.',
  whyRegionalExpansion: 'Regional Expansion',
  whyRegionalExpansionDesc: 'Platform architecture supports expansion to other South Asian markets with similar tax compliance challenges.',
  whyDiversifiedRevenue: 'Diversified Revenue',
  whyDiversifiedRevenueDesc: 'Revenue from SaaS subscriptions, per-filing fees, booth franchise model, and advisory services provides diversified income streams.',
  bmClientSubs: 'Client Subscriptions',
  bmClientSubsDesc: 'Annual tax management packages for individuals and businesses',
  bmPerFiling: 'Per-Filing Fees',
  bmPerFilingDesc: 'Transaction-based revenue for each tax return filed',
  bmBoothFranchise: 'Tax Booth Franchise',
  bmBoothFranchiseDesc: 'Franchise fees from national Tax Booth network operators',
  bmAdvisory: 'Advisory Services',
  bmAdvisoryDesc: 'Premium consulting via S&C Business Consultants',
  bmGovAPI: 'Government API Access',
  bmGovAPIDesc: 'Future: government-licensed data services',
  invStatRevenue: 'Revenue Pipeline',
  invStatCompanies: 'Subsidiary Companies',
  invStatDistricts: 'District Coverage',
  invStatTarget: 'Target: 2M Clients',

  // ── Careers ───────────────────────────────────────────────
  whyJobCuttingEdge: 'Cutting-Edge Tech',
  whyJobCuttingEdgeDesc: 'Work on AI, voice recognition, and multilingual mobile apps serving millions.',
  whyJobNationalImpact: 'National Impact',
  whyJobNationalImpactDesc: 'Directly improve the tax compliance of Sri Lankan citizens and businesses.',
  whyJobLearning: 'Learning Culture',
  whyJobLearningDesc: 'Regular training, mentorship programs, and access to professional certifications.',
  whyJobGrowth: 'Growth Opportunities',
  whyJobGrowthDesc: 'Fast-growing company with clear career paths across technology, advisory, and operations.',
  jobFullTime: 'Full-time',
  jobContract: 'Contract',
  jobColomboPH: 'Colombo',
  jobMultiLoc: 'Multiple Locations',
  jobIslandWide: 'Island-wide',
  jobTechDept: 'Technology',
  jobAdvisoryDept: 'Advisory',
  jobOpsDept: 'Operations',
  jobReactTitle: 'React / TypeScript Developer',
  jobReactDesc: 'Build and maintain the MyTax web platform using React, TypeScript, and modern APIs.',
  jobFlutterTitle: 'Flutter Mobile Developer',
  jobFlutterDesc: 'Develop and enhance the MyTax mobile app for iOS and Android.',
  jobTaxConsultTitle: 'Tax Consultant',
  jobTaxConsultDesc: 'Assist clients with income tax filing, TIN registration, and compliance consultancy.',
  jobBoothTitle: 'Tax Booth Officer',
  jobBoothDesc: 'Operate Matrix Tax Booths across GS Divisions — help citizens with app onboarding and filing.',
  jobDataTitle: 'Data Analyst',
  jobDataDesc: 'Analyze client data to improve service delivery and build compliance risk dashboards.',
  jobSupportTitle: 'Customer Support Officer',
  jobSupportDesc: 'Handle client queries via phone, email, and WhatsApp in English, Sinhala, and Tamil.',

  // ── Contact page ──────────────────────────────────────────
  contactEmailLabel: 'Email',
  contactHotlineLabel: 'Hotline',
  contactLocationLabel: 'Location',
  contactHoursLabel: 'Business Hours',
  contactWhatsAppLabel: 'WhatsApp',
  contactWebLabel: 'Web',
  contactLocationValue: 'Colombo, Sri Lanka',
  contactBusinessHoursValue: 'Mon–Fri: 8:30am – 5:00pm',
  responseCommitment1: 'All queries are responded to within 24 business hours.',
  responseCommitment2: 'Complaints are escalated to a senior officer within 48 hours.',
  complaintFormDesc: 'For formal complaints regarding our services, officers, or platform, please use the form above with subject "Complaint" — or contact us directly at:',
  complaintPdpaNote: 'All complaints are handled confidentially and in accordance with our PDPA-compliant data handling policy.',
  phFullName: 'Your full name',
  phEmail: 'you@example.com',
  phPhone: '+94 XX XXX XXXX',
  phSubject: 'Subject of your enquiry',
  phMessage: 'Write your message here...',

  // ── Legal content ─────────────────────────────────────────
  pdpaBadgeTitle: 'PDPA Compliant — Personal Data Protection Act No. 9 of 2022',
  pdpaBadgeDesc: "Matrix Investments PLC is committed to full compliance with Sri Lanka's Personal Data Protection Act. Your privacy is our legal obligation.",
  legalLastUpdated: 'Last updated: January 2026 · For queries: privacy@matrixinvestments.lk',
  legalPdpa1: 'We are fully compliant with the Personal Data Protection Act No. 9 of 2022 (Sri Lanka).',
  legalPdpa2: 'Your data is collected only with your explicit consent and used solely for the purposes you have agreed to.',
  legalPdpa3: 'We implement technical and organizational measures to protect your data against unauthorized access, loss, or alteration.',
  legalPdpa4: 'You may withdraw your consent at any time by contacting us at privacy@matrixinvestments.lk.',
  legalPriv1: 'We collect: NIC number, mobile number, email address, full name, location data, and tax-related financial information.',
  legalPriv2: 'We do NOT sell, rent, or share your personal data with third parties without your consent, except where required by law.',
  legalPriv3: 'Data is stored on encrypted servers with regular backups. Access is role-based and audit-logged.',
  legalPriv4: 'Cookies are used only for session management and do not track personal activity outside our platform.',
  legalTerms1: 'By using MyTax, you agree to provide accurate and truthful information for tax filing purposes.',
  legalTerms2: 'Matrix Investments PLC is not liable for tax penalties arising from inaccurate information provided by users.',
  legalTerms3: 'Unauthorized use, reverse engineering, or misuse of the platform will result in account termination.',
  legalTerms4: 'Services marked as "Paid" are subject to applicable fees as published on the platform.',
  legalData1: 'All data transmissions are encrypted using TLS 1.2+.',
  legalData2: 'Passwords are hashed using industry-standard algorithms and never stored in plain text.',
  legalData3: 'Two-factor authentication (OTP) is required for all account access.',
  legalData4: 'Regular security audits are performed by our compliance team.',
  legalConsent1: 'On registration, users provide explicit consent for data collection and processing.',
  legalConsent2: 'Consent is recorded with timestamp, user identity, and scope of permission.',
  legalConsent3: 'Users can view, update, or revoke their consent at any time via Account Settings.',
  legalConsent4: 'All consent records are maintained in our non-editable audit log as required by PDPA.',
  legalRet1: 'Active account data is retained for the duration of the client relationship.',
  legalRet2: 'Tax filing records are retained for a minimum of 5 years as required by IRD regulations.',
  legalRet3: 'Deleted account data is purged from production systems within 30 days.',
  legalRet4: 'Backup copies are deleted within 90 days of the production purge.',
  legalRight1: 'Right to Access: Request a copy of all data we hold about you.',
  legalRight2: 'Right to Rectification: Correct any inaccurate information in your profile.',
  legalRight3: 'Right to Erasure: Request deletion of your account and associated data.',
  legalRight4: 'Right to Data Portability: Export your data in a machine-readable format.',
  legalRight5: 'Lodge complaints with the Data Protection Authority of Sri Lanka.',

  // ── Services page ─────────────────────────────────────────
  tagIndividuals: 'Individuals',
  tagBusinesses: 'Businesses',
  tagRegistration: 'Registration',
  tagMonitoring: 'Monitoring',
  tagPrimary: 'Primary',
  platM1Label: 'Tax File Submission',
  platM2Label: 'TIN Number Status',
  platM3Label: 'Tax Calculator',
  platM5Label: 'Final Tax Computation',
  platM6Label: 'TIN Certificate Request',
  platM7Label: 'TIN Certificate Application',
  platM8Label: 'Tax Payer Information Update',
  platM9Label: 'Tax Administration Support',

  // ── Guide page ────────────────────────────────────────────
  guideUseOfTaxDesc: 'Learn how to use all MyTax digital services effectively, from TIN registration to annual tax filing.',
  guideUserGuideDesc: 'Step-by-step guide for individual taxpayers to navigate the MyTax platform and complete their filings.',
  guideAgentGuideDesc: 'Detailed guide for tax agents and officers on managing client portfolios and assignments.',
  guideAboutUsDesc: 'Learn about Matrix Investments PLC, our mission, group companies, and the services we offer across Sri Lanka.',
  guideHelpAIDesc: 'Interact with our AI-powered tax instructor in Sinhala, Tamil, or English — text and voice supported.',
  guideTaxCalendarDesc: 'Important tax deadlines, filing due dates, payment schedules, and penalty avoidance timeline for Sri Lanka.',
  smsRegTag: 'Registration',
  smsRegText: 'Client ID confirmation upon registration',
  smsAssignTag: 'Assignment',
  smsAssignText: 'When your work is assigned to an officer',
  smsDocsTag: 'Documents',
  smsDocsText: 'Alerts for pending or missing documents',
  smsDoneTag: 'Completed',
  smsDoneText: 'Notification when your tax work is done',
  smsInvoiceTag: 'Invoice',
  smsInvoiceText: 'Invoice generated with due date',
  smsConfirmedTag: 'Confirmed',
  smsConfirmedText: 'Tax return filing confirmation with reference number',
};

const sinhala: Record<string, string> = {
  appTitle: 'මයිටැක්ස්',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax ඩිජිටල් විසඳුම් (Pvt) Ltd',
  welcome: 'MyTax වෙත සාදරයෙන් පිළිගනිමු !',
  selectBeforeNext: 'ඊළඟට යාමට පෙර තෝරන්න',
  language: 'භාෂාව',
  respondIn: 'පිළිතුරු ආකාරය',
  text: 'පෙළ',
  voice: 'හඬ',
  next: 'ඊළඟ',
  declaration: 'ප්‍රකාශය',
  declarationBody:
    'සමාගම ඔබේ මූල්‍ය තොරතුරු බදු ඉදිරිපත් කිරීම සඳහා පමණක් භාවිතා කරනු ඇත. සේවා සපයන්නා ව්‍යාජ තොරතුරු සඳහා වගකිව යුතු නොවේ. ලේඛන ගබඩා කිරීම පරිශීලකයාගේ අනුමැතිය ඇතිව සිදු කෙරේ. ඔබේ බදු කටයුතු සම්බන්ධ නෛතික ප්‍රතිවිපාක සඳහා අපි වගකිව යුතු නොවේ.',
  userVerification: 'පරිශීලක සත්‍යාපනය',
  nicNumber: 'NIC අංකය:',
  mobileNumber: 'ජංගම අංකය:',
  underNic: '[ඔබේ NIC යටතේ]',
  note: '* සටහන',
  noteBody:
    '1. ලියාපදිංචි ජංගම අංකය ප්‍රවේශය සඳහා භාවිතා කළ යුතුය. තවද පද්ධතිය ඔබේ අනන්‍යතා තහවුරු කිරීම අවශ්‍ය වනු ඇත.',
  sendOtp: 'OTP යවා දැන් සත්‍යාපනය කරන්න',
  enterOtp: 'ඔබේ ජංගමයට යවන ලද OTP ඇතුළත් කරන්න',
  verifyOtp: 'OTP සත්‍යාපනය කරන්න',
  resendOtp: 'OTP නැවත යවන්න',
  verifiedMessage: 'පරිශීලකයා සාර්ථකව සත්‍යාපනය කරන ලදී. දැන් පුරනය වන්න!',
  login: 'පුරනය වන්න',
  fillAllFields: 'සියලු ක්ෂේත්‍ර පුරවන්න',
  enterCompleteOtp: 'සම්පූර්ණ OTP ඇතුළත් කරන්න',
  loginTitle: 'පුරනය වන්න',
  password: 'මුරපදය:',
  usePasskey: 'පාස්කී භාවිතා කරන්න',
  registerNew: 'නව ලියාපදිංචිය',
  forgotPassword: 'මුරපදය අමතකද?',
  loginFillFields: 'NIC සහ මුරපදය ඇතුළත් කරන්න',
  registerTitle: 'නව ලියාපදිංචිය!',
  fullName: 'සම්පූර්ණ නම: *',
  mobileNo: 'ජංගම අංකය: *',
  emailAddress: 'විද්‍යුත් තැපෑල: *',
  markLocation: 'ස්ථානය සලකුණු කරන්න: *',
  clickToMark: '-ස්ථානය සලකුණු කිරීමට ක්ලික් කරන්න-',
  district: 'දිස්ත්‍රික්කය:*',
  dsDivision: 'DS කොට්ඨාශය:*',
  gsDivision: 'GS කොට්ඨාශය:*',
  postalAddress: 'තැපැල් ලිපිනය:',
  postalNo: ': අංකය',
  addLine: ': රේඛාව එකතු කරන්න',
  createPassword: 'මුරපදය සාදන්න: *',
  usePasskeyBiometric: 'පාස්කී / ජෛව මිතික ප්‍රවේශය',
  verifyAndCreate: 'සත්‍යාපනය කර සාදන්න',
  registerFillFields: 'සියලු අවශ්‍ය ක්ෂේත්‍ර පුරවන්න',
  welcomeMyTax: 'MyTax වෙත සාදරයෙන් පිළිගනිමු !',
  thankYouReg: 'MyTax සේවා සඳහා ලියාපදිංචි වීමට ස්තූතියි!',
  happySupport:
    'රටේ සංවර්ධනය සඳහා ඔබේ බදු වගකීම සම්පූර්ණ කිරීමට සහාය වීමට අපි සතුටු වෙමු.',
  registeredClient: 'ඔබ බදු සේවාදායකයෙකු ලෙස ලියාපදිංචි වී ඇත.',
  clientCode: 'සේවාදායක කේතය:',
  clientName: 'සේවාදායක නම:',
  tinNumber: 'TIN අංකය:',
  contactNo: 'සම්බන්ධතා අංකය:',
  mailAddress: 'විද්‍යුත් ලිපිනය:',
  myTaxServices: 'මගේ බදු සේවා',
  guide: 'මාර්ගෝපදේශය',
  logout: 'පිටවීම',
  taxServicesTitle: 'MyTax සේවා',
  primaryService: 'ප්‍රාථමික සේවාව',
  supportService: 'සහාය සේවාව',
  m1: 'M1 - බදු ගොනු ඉදිරිපත් කිරීම',
  m2: 'M2 - TIN අංක තත්ත්වය (නිෂ්ශ්‍රේණිය)',
  m3: 'M3 - බදු කැල්කියුලේටරය (නිෂ්ශ්‍රේණිය)',
  m5: 'M5 - අවසාන බදු ගණනය (ගෙවිය යුතු)',
  m6: 'M6 - TIN සහතික ඉල්ලීම (ගෙවිය යුතු)',
  m7: 'M7 - TIN සහතික අයදුම්පත (ගෙවිය යුතු)',
  m8: 'M8 - බදු ගෙවන්නාගේ තොරතුරු යාවත්කාලීන (ගෙවිය යුතු)',
  m9: 'M9 - බදු පරිපාලන සහාය (ගෙවිය යුතු)',
  guideTitle: 'පොදු මාර්ගෝපදේශය',
  userGuideSection: 'පරිශීලක මාර්ගෝපදේශය',
  documentsForLogin: 'පුරනය සෑදීමට අවශ්‍ය ලේඛන',
  taxGeneralGuide: 'බදු පොදු මාර්ගෝපදේශය',
  taxFillingImportance: 'බදු ඉදිරිපත් කිරීමේ වැදගත්කම!',
  taxFilingTypes: 'බදු ඉදිරිපත් කිරීමේ වර්ග!',
  taxPayerRegDocs: 'බදු ගෙවන්නා ලියාපදිංචිය ලේඛන!',
  taxFilingPenalty: 'බදු ඉදිරිපත් නොකිරීමේ දඩ!',
  taxFilingReqDocs: 'බදු ඉදිරිපත් කිරීමට අවශ්‍ය ලේඛන!',
  taxInfoUpdateDocs: 'බදු ගෙවන්නාගේ තොරතුරු යාවත්කාලීන ලේඛන!',
  skip: 'මඟ හරින්න',
  heroTagline: 'ශ්‍රී ලංකාවේ විශ්වාසදායක ඩිජිටල් බදු ගෙවීමේ වේදිකාව',
  getStarted: 'ආරම්භ කරන්න',
  learnMore: 'තව දැනගන්න',
  signIn: 'පුරනය',
  services: 'සේවා',
  aboutUs: 'අප ගැන',
  home: 'මුල් පිටුව',
  footerTagline: 'ශ්‍රී ලාංකික බදු ගෙවන්නන් සඳහා සම්පූර්ණ බදු ගොනු කිරීමේ සහ TIN කළමනාකරණ විසඳුම්.',
  quickLinks: 'ශීඝ්‍ර සබැඳි',
  legal: 'නෛතික',
  contact: 'සම්බන්ධතා',
  privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය',
  termsOfService: 'සේවා නියම',
  faq: 'නිතර අසන ප්‍රශ්න',
  aboutTitle: 'MyTax ගැන',
  aboutDesc: 'MyTax යනු Matrix Investments PLC විසින් ශ්‍රී ලාංකික බදු ගෙවන්නන් සඳහා බදු ගොනු කිරීම සහ අනුකූලතාව සරල කිරීමට නිර්මාණය කරන ලද ඩිජිටල් වේදිකාවකි.',
  secureTitle: 'ආරක්ෂිත සහ විශ්වාසදායක',
  secureDesc: 'ඔබේ මූල්‍ය දත්ත ව්‍යවසාය මට්ටමේ ආරක්ෂාවෙන් ආරක්ෂා වේ.',
  fastTitle: 'වේගවත් සහ කාර්යක්ෂම',
  fastDesc: 'ඕනෑම තැනක සිට විනාඩි කිහිපයකින් බදු ගොනු සම්පූර්ණ කරන්න.',
  supportTitle: 'විශේෂඥ සහාය',
  supportDesc: 'අපගේ බදු විශේෂඥ කණ්ඩායම ඔබේ බදු ගමනේ සෑම පියවරකටම සහාය දක්විනු ඇත.',

  about: 'ගැන',
  groupCompanies: 'සමූහ සමාගම්',
  investorRelations: 'ආයෝජක සබඳතා',
  careers: 'රැකියා',
  contactComplaints: 'සම්බන්ධතා & පැමිණිලි',
  legalPrivacy: 'නෛතික & රහස්‍යතාව',
  more: 'තව',
  phoneTab: 'දුරකථන අංකය',
  emailTab: 'විද්‍යුත් තැපෑල',
  verifyViaPhone: 'දුරකථනය හරහා OTP සත්‍යාපනය',
  verifyViaEmail: 'විද්‍යුත් තැපෑල හරහා OTP සත්‍යාපනය',
  emailInput: 'විද්‍යුත් තැපෑල:',
  aboutPageTitle: 'Matrix Investments PLC ගැන',
  aboutPageDesc: 'නව්‍යකරණය, අඛණ්ඩතාව සහ ඇතුළත් කිරීම හරහා ශ්‍රී ලංකාවේ වඩාත්ම විශ්වාසදායක ඩිජිටල් බදු යටිතල ගොඩනැඟීම.',
  aboutPageMission: 'අපගේ මෙහෙවෙර',
  aboutPageMissionDesc: 'ශ්‍රී ලාංකික සෑම බදු ගෙවන්නෙකුටම ගැළෙනසුළු, නිවැරදි සහ දැරිය හැකි ඩිජිටල් බදු සේවා සැපයීම — තාක්ෂණය හරහා ශ්‍රමසාධ්‍ය ලේඛනකරණය ඉවත් කිරීම.',
  aboutPageVision: 'අපගේ දර්ශනය',
  aboutPageVisionDesc: '2030 වන විට AI-추진 මාර්ගෝපදේශය සහිතව ලක්ෂ 20+ ක් බදු ගෙවන්නන්ට සහාය වීමට දකුණු ආසියාවේ ප්‍රමුඛ ඩිජිටල් බදු වේදිකාව බවට පත් වීම.',
  aboutMatrixDesc1: 'Matrix Investments PLC යනු ශ්‍රී ලාංකික බදු ගෙවන්නන් සහ ආදායම් දෙපාර්තමේන්තුව අතර පරතරය පිරවීමට ස්ථාපිත, TIN ලියාපදිංචියේ සිට වාර්ෂික බදු ගොනු කිරීම දක්වා විසඳුම් සපයන මූල්‍ය තාක්ෂණ ශ්‍රී ලාංකික රක්ෂාකාරී සමාගමකි.',
  aboutMatrixDesc2: 'අපගේ සමාගම් කණ්ඩායම ඩිජිටල් වේදිකා, ජාතික බදු ඇතිකළු, මූල්‍ය උපදේශන සහ අනුකූලතා කළමනාකරණය හරහා ක්‍රියාත්මක වේ.',
  groupPageTitle: 'අපගේ සමූහ සමාගම්',
  groupPageDesc: 'Matrix Investments PLC ශ්‍රී ලංකාවේ බදු, මූල්‍ය සහ තාක්ෂණ සේවා කෙරෙහි අවධානය යොමු කළ විශේෂිත අනුෂ්ඨාන හයක් (6) හරහා ක්‍රියාත්මක වේ.',
  investorPageTitle: 'ආයෝජක සබඳතා',
  investorPageDesc: 'Matrix Investments PLC විනිවිදභාවය, තිරස්ථාරී වර්ධනය සහ සියලු ස්‍ථාවරකරුවන්ට වටිනාකම ලබා දීමට කැපවී සිටී.',
  whyInvest: 'Matrix හි ආයෝජනය කළ යුත්තේ ඇයි',
  investorContact: 'ආයෝජක ගැටළු සඳහා: investors@matrix.lk',
  careersPageTitle: 'Matrix හි රැකියා',
  careersPageDesc: 'ශ්‍රී ලංකාවේ වේගයෙන් වර්ධනය වන ඩිජිටල් බදු වේදිකාවට සම්බන්ධ වන්න.',
  openPositions: 'ලබා ගත හැකි රැකියා',
  applyNow: 'දැන් ඉල්ලුම් කරන්න',
  noOpenings: 'දැනට ලබා ගත හැකි රැකියා නොමැත. careers@matrix.lk හෝ ඔබේ CV යවන්න.',
  whyUs: 'අප සමඟ ක්‍රියා කළ යුත්තේ ඇයි',
  contactPageTitle: 'සම්බන්ධතා & පැමිණිලි',
  contactPageDesc: 'ඔබේ ප්‍රතිපෝෂණය අප තකා ගනිමු. ඕනෑම නාලිකාවක් හරහා අප වෙත ළඟා වෙන්න.',
  contactFormName: 'සම්පූර්ණ නම',
  contactFormEmail: 'විද්‍යුත් තැපෑල',
  contactFormPhone: 'දුරකතන අංකය',
  contactFormSubject: 'විෂය',
  contactFormMessage: 'ඔබේ පණිවිඩය',
  submitBtn: 'ඉදිරිපත් කරන්න',
  complaintSection: 'පැමිණිල්ලක් ඉදිරිපත් කරන්න',
  getInTouch: 'සම්බන්ධ වෙන්න',
  thankYouContact: 'ස්තූතියි! අපි පැය 24 ක් ඇතුළත ප්‍රතිචාර දක්වන්නෙමු.',
  legalPageTitle: 'නෛතික & රහස්‍යතාව',
  legalPageDesc: 'Matrix Investments PLC ශ්‍රී ලංකාවේ PDPA ට අනුකූලව ඔබේ පෞද්ගලික දත්ත ආරක්ෂා කිරීමට කැපවී සිටී.',
  pdpaTitle: 'PDPA අනුකූලතාව',
  pdpaDesc: 'ශ්‍රී ලංකා පෞද්ගලික දත්ත ආරක්ෂණ පනතට (2022) යටත්ව, ඔබේ දත්ත ඔබේ සෘජු (explicit) කැමැත්ත ඇතිව පමණක් රැස් කෙරේ.',
  privacyPolicyFull: 'රහස්‍යතා ප්‍රතිපත්තිය',
  termsOfServiceFull: 'සේවා නියම',
  dataProtection: 'දත්ත ආරක්ෂාව',
  consentFramework: 'කැමැත්ත රාමුව',
  dataRetention: 'දත්ත රඳවා ගැනීම',
  yourRights: 'ඔබේ අයිතිවාසිකම්',
  servicesPageTitle: 'අපගේ සේවාවන්',
  servicesPageDesc: 'ශ්‍රී ලංකාව පුරා පුද්ගලයන් සහ ව්‍යාපාරයන් සඳහා සම්පූර්ණ බදු සහ මූල්‍ය සේවාවන්.',
  individualTaxFiling: 'තනි පුද්ගල බදු ගොනු කිරීම',
  individualTaxDesc: 'රැකියා ලාභීන්, ස්වයං රැකියා සහ වෘත්තිකයන් සඳහා සම්පූර්ණ ආදායම් බදු ගොනු කිරීම.',
  businessTaxFiling: 'ව්‍යාපාරික බදු ගොනු කිරීම',
  businessTaxDesc: 'සෑම ප්‍රමාණයකම ව්‍යාපාරයන් සඳහා ආයතනික ආදායම් බදු සහ VAT ගොනු කිරීම.',
  tinRegistration: 'TIN ලියාපදිංචිය',
  tinRegistrationDesc: 'TIN ඉල්ලුම් සහ ලියාපදිංචිය. ආදායම් දෙපාර්තමේන්තුව සමඟ සම්පූර්ණ ක්‍රියාවලිය.',
  complianceMonitoring: 'අනුකූලතා නිරීක්ෂණය',
  complianceMonitoringDesc: 'ඔබේ බදු බාධ්‍යතාවන්, නිවසේ දිනයන්, දඩ ලකුණු සහ අවදානම් දර්ශක නිරන්තර නිරීක්ෂණය.',
  guidePageTitle: 'මාර්ගෝපදේශ සහ සම්පත්',
  guidePageDesc: 'ඔබේ බදු බාධ්‍යතාව තේරුම් ගැනීමට සහ අපගේ වේදිකාව effectively භාවිතා කිරීමට නිෂ්ශ්‍රේණිය ශික්ෂණ සම්පත්.',
  guideUseOfTaxServices: 'බදු සේවා භාවිතය',
  guideUserGuide: 'පරිශීලක මාර්ගෝපදේශය',
  guideAgentGuide: 'නියෝජිත මාර්ගෝපදේශය',
  guideAboutUs: 'අප ගැන',
  guideHelpAI: 'AI සහාය උපදේශකය',
  guideTaxCalendar: 'බදු දිනදර්ශනය',
  freeOfCharge: 'නිෂ්ශ්‍රේණිය',
  watchNow: 'දැන් නරඹන්න',
  comingSoon: 'ළඟදීම',

  // ── General UI ────────────────────────────────────────────
  paid: 'ගෙවිය යුතු',
  free: 'නිෂ්ශ්‍රේණිය',
  guideNote: 'සම්පූර්ණ මාර්ගෝපදේශය ළඟදීම',
  subsidiaryServices: 'අනුබද්ධ සේවා',
  groupStructure: 'සමූහ ව්‍යූහය',
  groupStructureNote: 'සියලුම අනුබද්ධ ආයතන Matrix Investments PLC හි මූලෝපායික දිශානතිය යටතේ ක්‍රියාත්මක වේ.',
  partnerWithUs: 'අප සමඟ හවුල් වන්න',
  partnerWithUsDesc: 'ඩිජිටල් බදු පරිවර්තනය පිළිබඳ අපගේ මෙහෙයුමට සමපාත වන මූලෝපායික ආයෝජකයින් සහ හවුල්කරුවන් අපි සාදරයෙන් පිළිගනිමු.',
  dontSeeRole: "ඔබේ භූමිකාව නොපෙනේද?",
  dontSeeRoleDesc: "ඔබේ CV එක අපගේ මානව සම්පත් කණ්ඩායමට එවන්න.",
  sendAnother: 'තවත් එකක් යවන්න',
  sending: 'යවමින්...',
  reviewAndRespond: 'අපගේ කණ්ඩායම ඔබේ පණිවිඩය සමාලෝචනය කර ඉක්මනින් ප්‍රතිචාර දක්වනු ඇත.',
  taxFilingComplianceTitle: 'බදු ගොනු කිරීම සහ අනුකූලතාව',
  myTaxDigitalServices: 'MyTax ඩිජිටල් සේවා',
  readyToFile: 'ඔබේ බදු ගොනු කිරීමට සූදානම්ද?',
  readyToFileDesc: 'මිනිත්තු කිහිපයකින් ඔබේ ගිණුම සාදා බදු අනුකූලතාව අපට භාර දෙන්න.',
  investmentCase: 'ආයෝජන අවස්ථාව',
  cultureBenefits: 'සංස්කෘතිය සහ ප්‍රතිලාභ',
  currentOpenings: 'දැනට පවතින පුරප්පාඩු',
  coreServices: 'මූලික සේවා',
  platformModules: 'වේදිකා මොඩියුල',
  videoGuidesTitle: 'බදු සරල මාර්ගෝපදේශ වීඩියෝ',
  smsAlertsTitle: 'SMS ඇඟවීම් දැනුම්දීම්',
  smsAlertsDesc: 'ඔබේ බදු ගමනේ සෑම පියවරක් සඳහාම ස්වයංක්‍රීය SMS දැනුම්දීම් සමඟ දැනුවත්ව සිටින්න:',
  businessModelTitle: 'ව්‍යාපාර ආකෘති දළ විශ්ලේෂණය',

  // ── About page stats ─────────────────────────────────────
  statsClients: 'සේවාදායකයින්',
  statsYears: 'වසර ගණනාවක අත්දැකීම්',
  statsTaxReturns: 'බදු වාර්තා ගොනු කර ඇත',
  statsDistricts: 'ආවරණය වන දිස්ත්‍රික්ක',

  // ── S&C service categories ────────────────────────────────
  scAccounts: 'ගිණුම්',
  scProposals: 'යෝජනා',
  scInventory: 'ඉන්වෙන්ටරි කළමනාකරණය',
  scTaxCategory: 'බදු',
  scCompanyReg: 'සමාගම් ලියාපදිංචි කිරීම්',
  scSecretarial: 'සමාගම් ලේකම් වැඩ',
  scRealEstate: 'දේපළ වෙළදාම්',
  scMonthlyFinance: 'මාසික මූල්‍ය අධීක්ෂණය',
  scMonthlyAccounts: 'මාසික ගිණුම්',
  scProfitReports: 'ව්‍යාපාර ලාභ වාර්තා',
  scLoanAccounts: 'ණය අරමුණු ගිණුම්',
  scAnnualAccounts: 'වාර්ෂික ගිණුම්',
  scLoanProposal: 'ණය යෝජනාව',
  scBusinessProposal: 'ව්‍යාපාර යෝජනාව',
  scStockVerification: 'තොග සත්‍යාපනය',
  scDigitalStock: 'ඩිජිටල් තොග ගණනය කිරීම්',
  scIncomeTaxFiling: 'ආදායම් බදු ගොනු කිරීම',
  scIncomeTaxReg: 'ආදායම් බදු ලියාපදිංචිය',
  scVatConsult: 'VAT උපදේශන',
  scTaxConsult: 'බදු උපදේශන',
  scBusinessReg: 'ව්‍යාපාර ලියාපදිංචිය',
  scCharityReg: 'පුණ්‍යායතන ලියාපදිංචිය',
  scAnnualReturn: 'වාර්ෂික වාර්තා ගොනු කිරීම',
  scSecretary: 'ලේකම් සේවා',
  scDealAdvisory: 'ගනුදෙනු උපදේශනය',

  // ── Digital tools ─────────────────────────────────────────
  toolMyTaxApp: 'MyTax ඩිජිටල් යෙදුම',
  toolGuidanceVideos: 'බදු සරල මාර්ගෝපදේශ වීඩියෝ',
  toolUserGuideLabel: 'පරිශීලක මාර්ගෝපදේශය',
  toolAIInstructor: 'AI බදු උපදේශක',
  toolTaxCalendar: 'බදු දිනදර්ශනය',
  toolAgentGuide: 'නියෝජිත මාර්ගෝපදේශය',

  // ── Group Companies ───────────────────────────────────────
  company1Tagline: 'ව්‍යාපාර සහ බදු උපදේශන විශිෂ්ටත්වය',
  company1Desc: 'ශ්‍රී ලංකාව පුරා ව්‍යාපාර සහ පුද්ගලයින් සඳහා පුළුල් ගිණුම්කරණ, බදු, සමාගම් ලියාපදිංචි කිරීමේ සේවා.',
  company2Tagline: 'ඩිජිටල් බදු නව්‍යකරණය',
  company2Desc: 'Matrix Investments PLC හි තාක්ෂණික අංශය, බදු ගොනු කිරීම සහ අනුකූලතා කළමනාකරණය සඳහා MyTax ඩිජිටල් වේදිකාව මෙහෙයවයි.',
  company3Tagline: 'ජාතික බදු ප්‍රවේශ ස්ථාන',
  company3Desc: 'Matrix බදු කුටි ජාතික වැඩසටහන කළමනාකරණය කරයි.',
  company4Tagline: 'ආයෝජන සහ මූල්‍ය උපදේශනය',
  company4Desc: 'ආයතනික සහ තනි සේවාදායකයින් සඳහා විශේෂඥ මූල්‍ය උපදේශන සහ ආයෝජන සැලසුම් සැපයීම.',
  company5Tagline: 'නියාමන අනුකූලතා කළමනාකරණය',
  company5Desc: 'නියාමන අනුකූලතා අධීක්ෂණය සහ රජයේ සම්බන්ධතා සේවා සඳහා විශේෂිත වේ.',
  company6Tagline: 'බදු සඳහා දත්ත බුද්ධිය',
  company6Desc: 'සේවාදායක දත්ත සමුදා කළමනාකරණය සහ AI මත පදනම් වූ බදු ප්‍රශ්නාවලි පද්ධති සඳහා සහාය වන දත්ත විශ්ලේෂණ.',
  svcAccounts: 'ගිණුම්',
  svcTaxFiling: 'බදු ගොනු කිරීම',
  svcCompanyReg: 'සමාගම් ලියාපදිංචි කිරීම්',
  svcInventoryMgmt: 'ඉන්වෙන්ටරි කළමනාකරණය',
  svcRealEstate: 'දේපළ වෙළදාම්',
  svcProposals: 'යෝජනා',
  svcSecretarialWorks: 'ලේකම් වැඩ',
  svcMyTaxApp: 'MyTax යෙදුම',
  svcDigitalTaxFiling: 'ඩිජිටල් බදු ගොනු කිරීම',
  svcTINServices: 'TIN සේවා',
  svcComplianceTools: 'අනුකූලතා මෙවලම්',
  svcAIAssistant: 'AI බදු සහායක',
  svcTINRegistration: 'TIN ලියාපදිංචිය',
  svcAppOnboarding: 'යෙදුම් ඇතුළත් කිරීම',
  svcVoiceFiling: 'හඬ ගොනු කිරීම',
  svcPaymentGuidance: 'ගෙවීම් මාර්ගෝපදේශය',
  svcFinancialAdvisory: 'මූල්‍ය උපදේශනය',
  svcInvestmentPlanning: 'ආයෝජන සැලසුම් කිරීම',
  svcCapitalManagement: 'ප්‍රාග්ධන කළමනාකරණය',
  svcRiskAssessment: 'අවදානම් තක්සේරුව',
  svcComplianceAudits: 'අනුකූලතා විගණන',
  svcRiskManagement: 'අවදානම් කළමනාකරණය',
  svcGovernmentLiaison: 'රජයේ සම්බන්ධතා',
  svcRegulatoryReporting: 'නියාමන වාර්තාකරණය',
  svcDataAnalytics: 'දත්ත විශ්ලේෂණ',
  svcClientDatabase: 'සේවාදායක දත්ත සමුදා කළමනාකරණය',
  svcReportingTools: 'වාර්තාකරණ මෙවලම්',

  // ── Investor Relations ────────────────────────────────────
  whyGrowingMarket: 'වර්ධනය වන වෙළඳපොළ',
  whyGrowingMarketDesc: 'ශ්‍රී ලංකාවේ මිලියන 10+ බදු ගෙවිය හැකි පුද්ගලයින් සිටී. දැනට වාර්තා ගොනු කරන්නේ 30% කට වඩා අඩු පිරිසකි.',
  whyRegulatoryTailwind: 'නියාමන පසුබිම',
  whyRegulatoryTailwindDesc: 'ඩිජිටල් බදු ඉදිරිපත් කිරීම සහ TIN ලියාපදිංචිය සඳහා රජයේ නියෝග ඩිජිටල් වේදිකා වේගයෙන් සම්මත කර ගැනීමට හේතු වේ.',
  whyTechMoat: 'තාක්ෂණික බාධක',
  whyTechMoatDesc: 'AI බදු ප්‍රශ්නාවලිය, බහුභාෂා හඬ අතුරුමුහුණත සහ ජාතික කුටි ජාලය ශක්තිමත් තරඟකාරී බාධක නිර්මාණය කරයි.',
  whyGovPartnership: 'රජයේ හවුල්කාරිත්වය',
  whyGovPartnershipDesc: 'දත්ත ප්‍රවේශ API සහ ජාතික බදු කුටි සඳහා IRD සමඟ උපායමාර්ගික හවුල්කාරිත්වය.',
  whyRegionalExpansion: 'කලාපීය ව්‍යාප්තිය',
  whyRegionalExpansionDesc: 'සමාන බදු අනුකූලතා අභියෝග සහිත අනෙකුත් දකුණු ආසියානු වෙළඳපල සඳහා වේදිකාව සහාය දක්වයි.',
  whyDiversifiedRevenue: 'විවිධාංගීකරණය වූ ආදායම',
  whyDiversifiedRevenueDesc: 'SaaS දායකත්වයන්, ගොනු කිරීමේ ගාස්තු, කුටි බලයලත් ආකෘතිය සහ උපදේශන සේවා වලින් ආදායම.',
  bmClientSubs: 'සේවාදායක දායකත්වයන්',
  bmClientSubsDesc: 'පුද්ගලයින් සහ ව්‍යාපාර සඳහා වාර්ෂික බදු කළමනාකරණ පැකේජ',
  bmPerFiling: 'ගොනු කිරීමේ ගාස්තු',
  bmPerFilingDesc: 'ගොනු කරන ලද සෑම බදු වාර්තාවක් සඳහාම ගනුදෙනු මත පදනම් වූ ආදායම',
  bmBoothFranchise: 'බදු කුටි බලයලත්',
  bmBoothFranchiseDesc: 'ජාතික බදු කුටි ජාල ක්‍රියාකරුවන්ගෙන් බලයලත් ගාස්තු',
  bmAdvisory: 'උපදේශන සේවා',
  bmAdvisoryDesc: 'S&C Business Consultants හරහා වාරික උපදේශනය',
  bmGovAPI: 'රජයේ API ප්‍රවේශය',
  bmGovAPIDesc: 'අනාගතය: රජයේ බලපත්‍රලාභී දත්ත සේවා',
  invStatRevenue: 'ආදායම් නාලිකාව',
  invStatCompanies: 'අනුබද්ධ සමාගම්',
  invStatDistricts: 'දිස්ත්‍රික් ආවරණය',
  invStatTarget: 'ඉලක්කය: සේවාදායකයින් මිලියන 2',

  // ── Careers ───────────────────────────────────────────────
  whyJobCuttingEdge: 'අති නවීන තාක්ෂණය',
  whyJobCuttingEdgeDesc: 'මිලියන ගණනකට සේවය කරන AI, හඬ හඳුනාගැනීම සහ බහුභාෂා ජංගම යෙදුම් මත වැඩ කරන්න.',
  whyJobNationalImpact: 'ජාතික බලපෑම',
  whyJobNationalImpactDesc: 'ශ්‍රී ලංකා පුරවැසියන්ගේ සහ ව්‍යාපාරවල බදු අනුකූලතාවය සෘජුවම වැඩිදියුණු කරන්න.',
  whyJobLearning: 'ඉගෙනුම් සංස්කෘතිය',
  whyJobLearningDesc: 'නිතිපතා පුහුණුව, උපදේශන වැඩසටහන් සහ වෘත්තීය සහතික වෙත ප්‍රවේශය.',
  whyJobGrowth: 'වර්ධන අවස්ථා',
  whyJobGrowthDesc: 'තාක්ෂණය, උපදේශන සහ මෙහෙයුම් හරහා පැහැදිලි වෘත්තීය මාර්ග සහිත වේගයෙන් වර්ධනය වන සමාගම.',
  jobFullTime: 'පූර්ණ කාලීන',
  jobContract: 'කොන්ත්‍රාත්',
  jobColomboPH: 'කොළඹ',
  jobMultiLoc: 'බහු ස්ථාන',
  jobIslandWide: 'දිවයින පුරා',
  jobTechDept: 'තාක්ෂණික',
  jobAdvisoryDept: 'උපදේශන',
  jobOpsDept: 'මෙහෙයුම්',
  jobReactTitle: 'React / TypeScript සංවර්ධක',
  jobReactDesc: 'React, TypeScript සහ නවීන API භාවිතා කරමින් MyTax වෙබ් වේදිකාව ගොඩනඟා නඩත්තු කරන්න.',
  jobFlutterTitle: 'Flutter ජංගම සංවර්ධක',
  jobFlutterDesc: 'iOS සහ Android සඳහා MyTax ජංගම යෙදුම සංවර්ධනය කර වැඩිදියුණු කරන්න.',
  jobTaxConsultTitle: 'බදු උපදේශක',
  jobTaxConsultDesc: 'ආදායම් බදු ගොනු කිරීම, TIN ලියාපදිංචිය සහ අනුකූලතා උපදේශනය සමඟ සේවාදායකයින්ට සහාය වන්න.',
  jobBoothTitle: 'බදු කුටි නිලධාරී',
  jobBoothDesc: 'GS කොට්ඨාශ හරහා Matrix බදු කුටි ක්‍රියාත්මක කරන්න.',
  jobDataTitle: 'දත්ත විශ්ලේෂක',
  jobDataDesc: 'සේවා සැපයීම වැඩිදියුණු කිරීමට සහ අනුකූලතා අවදානම් උපකරණ පුවරු තැනීමට සේවාදායක දත්ත විශ්ලේෂණය කරන්න.',
  jobSupportTitle: 'පාරිභෝගික සහාය නිලධාරී',
  jobSupportDesc: 'ඉංග්‍රීසි, සිංහල සහ දෙමළ භාෂාවෙන් දුරකථන, විද්‍යුත් තැපෑල සහ WhatsApp හරහා සේවාදායක විමසුම් හසුරුවන්න.',

  // ── Contact page ──────────────────────────────────────────
  contactEmailLabel: 'විද්‍යුත් තැපෑල',
  contactHotlineLabel: 'ක්ෂණික ඇමතුම්',
  contactLocationLabel: 'ස්ථානය',
  contactHoursLabel: 'ව්‍යාපාරික වේලාවන්',
  contactWhatsAppLabel: 'WhatsApp',
  contactWebLabel: 'වෙබ්',
  contactLocationValue: 'කොළඹ, ශ්‍රී ලංකාව',
  contactBusinessHoursValue: 'සඳුදා-සිකු: පෙ.ව 8:30 - ප.ව 5:00',
  responseCommitment1: 'සියලුම විමසුම් සඳහා ව්‍යාපාරික පැය 24ක් ඇතුළත ප්‍රතිචාර දක්වනු ලැබේ.',
  responseCommitment2: 'පැමිණිලි පැය 48ක් ඇතුළත ජ්‍යෙෂ්ඨ නිලධාරියෙකු වෙත යොමු කෙරේ.',
  complaintFormDesc: 'අපගේ සේවාවන්, නිලධාරීන් හෝ වේදිකාව සම්බන්ධයෙන් විධිමත් පැමිණිලි සඳහා, කරුණාකර "පැමිණිල්ල" විෂයය සමඟ ඉහත පෝරමය භාවිතා කරන්න.',
  complaintPdpaNote: 'සියලුම පැමිණිලි රහසිගතව සහ අපගේ PDPA අනුකූල දත්ත හැසිරවීමේ ප්‍රතිපත්තියට අනුකූලව හසුරුවනු ලැබේ.',
  phFullName: 'ඔබේ සම්පූර්ණ නම',
  phEmail: 'ඔබ@උදාහරණය.com',
  phPhone: '+94 XX XXX XXXX',
  phSubject: 'ඔබගේ විමසුමේ විෂයය',
  phMessage: 'ඔබේ පණිවිඩය මෙහි ලියන්න...',

  // ── Legal content ─────────────────────────────────────────
  pdpaBadgeTitle: 'PDPA අනුකූල - 2022 අංක 9 දරන පුද්ගලික දත්ත ආරක්ෂණ පනත',
  pdpaBadgeDesc: "Matrix Investments PLC ශ්‍රී ලංකාවේ පුද්ගලික දත්ත ආරක්ෂණ පනතට පූර්ණ ලෙස අනුකූල වීමට කැපවී සිටී.",
  legalLastUpdated: 'අවසන් වරට යාවත්කාලීන කළේ: ජනවාරි 2026',
  legalPdpa1: 'අපි 2022 අංක 9 දරන පුද්ගලික දත්ත ආරක්ෂණ පනතට (ශ්‍රී ලංකාව) පූර්ණ ලෙස අනුකූල වෙමු.',
  legalPdpa2: 'ඔබේ දත්ත එකතු කරනු ලබන්නේ ඔබේ පැහැදිලි කැමැත්ත ඇතිව පමණි.',
  legalPdpa3: 'අනවසර ප්‍රවේශය, අලාභය හෝ වෙනස් කිරීම් වලින් ඔබේ දත්ත ආරක්ෂා කිරීමට අපි තාක්ෂණික සහ ආයතනික පියවරයන් ක්‍රියාත්මක කරමු.',
  legalPdpa4: 'ඔබට ඕනෑම අවස්ථාවක ඔබේ කැමැත්ත ඉල්ලා අස්කර ගත හැක.',
  legalPriv1: 'අපි එකතු කරන්නේ: ජා.හැ.ප අංකය, ජංගම දුරකථන අංකය, විද්‍යුත් තැපැල් ලිපිනය, සම්පූර්ණ නම, ස්ථාන දත්ත සහ බදු සම්බන්ධ මූල්‍ය තොරතුරු.',
  legalPriv2: 'නීතියෙන් අවශ්‍ය වන අවස්ථා වලදී හැර, ඔබගේ කැමැත්ත නොමැතිව අපි ඔබගේ පුද්ගලික දත්ත තෙවන පාර්ශවයන් සමඟ විකිණීම, කුලියට දීම හෝ බෙදාගැනීම නොකරමු.',
  legalPriv3: 'දත්ත නිතිපතා උපස්ථ සමඟ සංකේතනය කරන ලද සේවාදායක මත ගබඩා කර ඇත.',
  legalPriv4: 'කුකීස් සැසි කළමනාකරණය සඳහා පමණක් භාවිතා වේ.',
  legalTerms1: 'MyTax භාවිතා කිරීමෙන්, බදු ගොනු කිරීමේ අරමුණු සඳහා නිවැරදි සහ සත්‍ය තොරතුරු සැපයීමට ඔබ එකඟ වේ.',
  legalTerms2: 'පරිශීලකයින් විසින් සපයනු ලබන සාවද්‍ය තොරතුරු හේතුවෙන් පැන නගින බදු දඩ සඳහා Matrix Investments PLC වගකියනු නොලැබේ.',
  legalTerms3: 'වේදිකාවේ අනවසර භාවිතය හෝ අනිසි භාවිතය ගිණුම අවසන් කිරීමට හේතු වනු ඇත.',
  legalTerms4: '"ගෙවන ලද" ලෙස සලකුණු කර ඇති සේවාවන් අදාළ ගාස්තු වලට යටත් වේ.',
  legalData1: 'සියලුම දත්ත සම්ප්‍රේෂණ TLS 1.2+ භාවිතයෙන් සංකේතනය කර ඇත.',
  legalData2: 'මුරපද හැෂ් කර ඇති අතර කිසිවිටෙක සරල පෙළෙහි ගබඩා නොවේ.',
  legalData3: 'සියලුම ගිණුම් ප්‍රවේශ සඳහා ද්වි-සාධක සත්‍යාපනය (OTP) අවශ්‍ය වේ.',
  legalData4: 'නිත්‍ය ආරක්ෂක විගණන සිදු කරනු ලැබේ.',
  legalConsent1: 'ලියාපදිංචි වීමේදී, දත්ත රැස් කිරීම සහ සැකසීම සඳහා පරිශීලකයින් පැහැදිලි කැමැත්ත ලබා දෙයි.',
  legalConsent2: 'කැමැත්ත වාර්තා කර ඇත.',
  legalConsent3: 'පරිශීලකයින්ට ගිණුම් සැකසීම් හරහා ඕනෑම අවස්ථාවක ඔවුන්ගේ කැමැත්ත බැලීමට, යාවත්කාලීන කිරීමට හෝ අවලංගු කිරීමට හැකිය.',
  legalConsent4: 'සියලුම කැමැත්ත වාර්තා අපගේ විගණන ලොගයේ නඩත්තු කෙරේ.',
  legalRet1: 'සේවාදායක සම්බන්ධතාවයේ කාලසීමාව සඳහා සක්‍රීය ගිණුම් දත්ත රඳවා ගනු ලැබේ.',
  legalRet2: 'බදු ගොනු කිරීමේ වාර්තා අවම වශයෙන් වසර 5 ක් රඳවා තබා ගනී.',
  legalRet3: 'මකා දැමූ ගිණුම් දත්ත දින 30ක් ඇතුළත පද්ධතිවලින් ඉවත් කරනු ලැබේ.',
  legalRet4: 'නිෂ්පාදන ඉවත් කිරීමෙන් දින 90ක් ඇතුළත උපස්ථ පිටපත් මකා දමනු ලැබේ.',
  legalRight1: 'ප්‍රවේශ වීමේ අයිතිය: අප සතුව ඇති ඔබගේ සියලු දත්තවල පිටපතක් ඉල්ලන්න.',
  legalRight2: 'නිවැරදි කිරීමේ අයිතිය: ඔබගේ පැතිකඩෙහි ඇති ඕනෑම සාවද්‍ය තොරතුරු නිවැරදි කරන්න.',
  legalRight3: 'මකා දැමීමේ අයිතිය: ඔබගේ ගිණුම සහ අදාළ දත්ත මකා දැමීම ඉල්ලන්න.',
  legalRight4: 'දත්ත ගෙන යාමේ අයිතිය: යන්ත්‍රයෙන් කියවිය හැකි ආකෘතියකින් ඔබගේ දත්ත අපනයනය කරන්න.',
  legalRight5: 'ශ්‍රී ලංකාවේ දත්ත ආරක්ෂණ අධිකාරිය වෙත පැමිණිලි ඉදිරිපත් කරන්න.',

  // ── Services page ─────────────────────────────────────────
  tagIndividuals: 'පුද්ගලයන්',
  tagBusinesses: 'ව්‍යාපාර',
  tagRegistration: 'ලියාපදිංචිය',
  tagMonitoring: 'අධීක්ෂණය',
  tagPrimary: 'ප්‍රාථමික',
  platM1Label: 'බදු ගොනු ඉදිරිපත් කිරීම',
  platM2Label: 'TIN අංක තත්ත්වය',
  platM3Label: 'බදු කැල්කියුලේටරය',
  platM5Label: 'අවසාන බදු ගණනය',
  platM6Label: 'TIN සහතික ඉල්ලීම',
  platM7Label: 'TIN සහතික අයදුම්පත',
  platM8Label: 'බදු ගෙවන්නාගේ තොරතුරු යාවත්කාලීන',
  platM9Label: 'බදු පරිපාලන සහාය',

  // ── Guide page ────────────────────────────────────────────
  guideUseOfTaxDesc: 'TIN ලියාපදිංචියේ සිට වාර්ෂික බදු ගොනු කිරීම දක්වා සියලුම MyTax ඩිජිටල් සේවා ඵලදායී ලෙස භාවිතා කරන ආකාරය ඉගෙන ගන්න.',
  guideUserGuideDesc: 'MyTax වේදිකාවේ සැරිසැරීමට සහ ඔවුන්ගේ ගොනු කිරීම් සම්පූර්ණ කිරීමට තනි බදු ගෙවන්නන් සඳහා පියවරෙන් පියවර මාර්ගෝපදේශය.',
  guideAgentGuideDesc: 'සේවාදායක අනුපාත සහ පැවරුම් කළමනාකරණය කිරීම පිළිබඳ බදු නියෝජිතයින් සහ නිලධාරීන් සඳහා සවිස්තරාත්මක මාර්ගෝපදේශය.',
  guideAboutUsDesc: 'Matrix Investments PLC, අපගේ මෙහෙවර, අනුබද්ධ සමාගම් සහ අපි ශ්‍රී ලංකාව පුරා ලබා දෙන සේවාවන් ගැන ඉගෙන ගන්න.',
  guideHelpAIDesc: 'අපගේ AI බලයෙන් ක්‍රියාත්මක වන බදු උපදේශක සමඟ සිංහල, දෙමළ හෝ ඉංග්‍රීසි භාෂාවෙන් අන්තර් ක්‍රියා කරන්න - පෙළ සහ හඬ සහාය දක්වයි.',
  guideTaxCalendarDesc: 'වැදගත් බදු කාලසීමාවන්, ගොනු කළ යුතු දිනයන්, ගෙවීම් කාලසටහන් සහ ශ්‍රී ලංකාව සඳහා දඬුවම් මඟහරවා ගැනීමේ කාලරාමුව.',
  smsRegTag: 'ලියාපදිංචිය',
  smsRegText: 'ලියාපදිංචි වූ පසු සේවාදායක හැඳුනුම්පත් තහවුරු කිරීම',
  smsAssignTag: 'පැවරුම',
  smsAssignText: 'ඔබේ කාර්යය නිලධාරියෙකුට පවරන විට',
  smsDocsTag: 'ලේඛන',
  smsDocsText: 'පොරොත්තු හෝ අස්ථානගත වූ ලේඛන සඳහා ඇඟවීම්',
  smsDoneTag: 'සම්පූර්ණයි',
  smsDoneText: 'ඔබේ බදු කටයුතු නිම වූ විට දැනුම්දීම',
  smsInvoiceTag: 'ඉන්වොයිසිය',
  smsInvoiceText: 'නියමිත දිනය සමඟ ඉන්වොයිසිය ජනනය කරන ලදී',
  smsConfirmedTag: 'තහවුරු කර ඇත',
  smsConfirmedText: 'යොමු අංකය සමඟ බදු වාර්තා ගොනු කිරීම තහවුරු කිරීම',
};

const tamil: Record<string, string> = {
  appTitle: 'மைடாக்ஸ்',
  companyName: 'Matrix Investments PLC',
  copyright: '© Matrix MyTax டிஜிட்டல் தீர்வுகள் (Pvt) Ltd',
  welcome: 'மைடாக்ஸ் க்கு வரவேற்கிறோம் !',
  selectBeforeNext: 'அடுத்ததற்கு முன் தேர்வு செய்யவும்',
  language: 'மொழி',
  respondIn: 'பதில் வகை',
  text: 'உரை',
  voice: 'குரல்',
  next: 'அடுத்து',
  declaration: 'அறிவிப்பு',
  declarationBody:
    'இந்த நிறுவனம் உங்கள் நிதி தகவல்களை வரி தாக்கல் மட்டுமே பயன்படுத்தும். சேவை வழங்குநர் பொய்யான அல்லது திருத்தப்பட்ட தகவல்களுக்கு பொறுப்பல்ல. ஆவணங்கள் சேமிப்பு பயனரின் அனுமதியோடு மேற்கொள்ளப்படும். உங்கள் வரி விவகாரங்களுக்கான சட்ட விளைவுகளுக்கு நாங்கள் பொறுப்பல்ல.',
  userVerification: 'பயனர் சரிபார்ப்பு',
  nicNumber: 'NIC எண்:',
  mobileNumber: 'மொபைல் எண்:',
  underNic: '[உங்கள் NIC கீழ்]',
  note: '* குறிப்பு',
  noteBody:
    '1. பதிவு செய்யப்பட்ட மொபைல் எண் அணுகலுக்கு பயன்படுத்தப்பட வேண்டும். மேலும் அமைப்பு உங்கள் அடையாள உறுதிப்படுத்தல் தேவைப்படும்.',
  sendOtp: 'OTP அனுப்பி சரிபார்க்கவும்',
  enterOtp: 'உங்கள் மொபைலுக்கு அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்',
  verifyOtp: 'OTP சரிபார்க்கவும்',
  resendOtp: 'OTP மீண்டும் அனுப்பவும்',
  verifiedMessage:
    'பயனர் வெற்றிகரமாக சரிபார்க்கப்பட்டார். இப்போது உள்நுழையலாம்!',
  login: 'உள்நுழைவு',
  fillAllFields: 'அனைத்து புலங்களையும் நிரப்பவும்',
  enterCompleteOtp: 'முழுமையான OTP ஐ உள்ளிடவும்',
  loginTitle: 'உள்நுழைவு',
  password: 'கடவுச்சொல்:',
  usePasskey: 'பாஸ்கீ பயன்படுத்து',
  registerNew: 'புதிதாக பதிவு செய்',
  forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
  loginFillFields: 'NIC மற்றும் கடவுச்சொல் உள்ளிடவும்',
  registerTitle: 'புதிதாக பதிவு செய்யுங்கள்!',
  fullName: 'முழு பெயர்: *',
  mobileNo: 'மொபைல் எண்: *',
  emailAddress: 'மின்னஞ்சல்: *',
  markLocation: 'இடத்தை குறிக்கவும்: *',
  clickToMark: '-இடத்தை குறிக்க கிளிக் செய்யவும்-',
  district: 'மாவட்டம்:*',
  dsDivision: 'DS பிரிவு:*',
  gsDivision: 'GS பிரிவு:*',
  postalAddress: 'தபால் முகவரி:',
  postalNo: ': எண்',
  addLine: ': வரி சேர்',
  createPassword: 'கடவுச்சொல் உருவாக்கு: *',
  usePasskeyBiometric: 'பாஸ்கீ / உயிரியல் அணுகல்',
  verifyAndCreate: 'சரிபார்த்து உருவாக்கு',
  registerFillFields: 'அனைத்து கட்டாயமான புலங்களையும் நிரப்பவும்',
  welcomeMyTax: 'MyTax க்கு வரவேற்கிறோம் !',
  thankYouReg: 'MyTax சேவைகளில் பதிவு செய்தமைக்கு நன்றி!',
  happySupport:
    'நாட்டின் வளர்ச்சிக்கான உங்கள் வரி பொறுப்பை நிறைவேற்ற உதவுவதில் மகிழ்ச்சி.',
  registeredClient:
    'நீங்கள் வரி வாடிக்கையாளராக பதிவு செய்யப்பட்டுள்ளீர்கள்.',
  clientCode: 'வாடிக்கையாளர் குறியீடு:',
  clientName: 'வாடிக்கையாளர் பெயர்:',
  tinNumber: 'TIN எண்:',
  contactNo: 'தொடர்பு எண்:',
  mailAddress: 'மின்னஞ்சல்:',
  myTaxServices: 'என் வரி சேவைகள்',
  guide: 'வழிகாட்டி',
  logout: 'வெளியேறு',
  taxServicesTitle: 'MyTax சேவைகள்',
  primaryService: 'முதன்மை சேவை',
  supportService: 'ஆதரவு சேவை',
  m1: 'M1 - வரி கோப்பு சமர்ப்பணம்',
  m2: 'M2 - TIN எண் நிலை (இலவசம்)',
  m3: 'M3 - வரி கணக்கீட்டி (இலவசம்)',
  m5: 'M5 - இறுதி வரி கணக்கீடு (கட்டண)',
  m6: 'M6 - TIN சான்றிதழ் கோரிக்கை (கட்டண)',
  m7: 'M7 - TIN சான்றிதழ் விண்ணப்பம் (கட்டண)',
  m8: 'M8 - வரி செலுத்துவோர் தகவல் புதுப்பிப்பு (கட்டண)',
  m9: 'M9 - வரி நிர்வாக ஆதரவு (கட்டண)',
  guideTitle: 'பொது வழிகாட்டி',
  userGuideSection: 'பயனர் வழிகாட்டி',
  documentsForLogin: 'உள்நுழைவு உருவாக்க தேவையான ஆவணங்கள்',
  taxGeneralGuide: 'வரி பொது வழிகாட்டி',
  taxFillingImportance: 'வரி தாக்கல் முக்கியத்துவம்!',
  taxFilingTypes: 'வரி தாக்கல் வகைகள்!',
  taxPayerRegDocs: 'வரி செலுத்துவோர் பதிவு ஆவணங்கள்!',
  taxFilingPenalty: 'வரி தவிர்ப்பு அபராதம்!',
  taxFilingReqDocs: 'வரி தாக்கல் தேவையான ஆவணங்கள்!',
  taxInfoUpdateDocs: 'வரி செலுத்துவோர் தகவல் புதுப்பிப்பு ஆவணங்கள்!',
  skip: 'தவிர்',
  heroTagline: 'இலங்கையின் நம்பகமான டிஜிட்டல் வரி தாக்கல் தளம்',
  getStarted: 'தொடங்குங்கள்',
  learnMore: 'மேலும் அறிக',
  signIn: 'உள்நுழைவு',
  services: 'சேவைகள்',
  aboutUs: 'எங்களை பற்றி',
  home: 'முகப்பு',
  footerTagline: 'இலங்கை வரி செலுத்துவோருக்கான முழுமையான வரி தாக்கல் மற்றும் TIN மேலாண்மை தீர்வுகள்.',
  quickLinks: 'விரைவு இணைப்புகள்',
  legal: 'சட்ட',
  contact: 'தொடர்பு',
  privacyPolicy: 'தனியுரிமைக் கொள்கை',
  termsOfService: 'சேவை விதிமுறைகள்',
  faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
  aboutTitle: 'MyTax பற்றி',
  aboutDesc: 'MyTax என்பது Matrix Investments PLC ஆல் இலங்கை வரி செலுத்துவோருக்கான டிஜிட்டல் தளமாகும்.',
  secureTitle: 'பாதுகாப்பான & நம்பகமான',
  secureDesc: 'உங்கள் நிதி தரவு நிறுவன தர பாதுகாப்புடன் பாதுகாக்கப்படுகிறது.',
  fastTitle: 'வேகமான & திறமையான',
  fastDesc: 'எங்கிருந்தும் சில நிமிடங்களில் வரி தாக்கல்களை முடிக்கவும்.',
  supportTitle: 'நிபுணர் ஆதரவு',
  supportDesc: 'எங்கள் வரி நிபுணர்கள் உங்கள் வரி பயணத்தின் ஒவ்வொரு படிக்கும் வழிகாட்டுவார்கள்.',

  about: 'பற்றி',
  groupCompanies: 'குழு நிறுவனங்கள்',
  investorRelations: 'முதலீட்டாளர் தொடர்பு',
  careers: 'வாழ்க்கை வாய்ப்புகள்',
  contactComplaints: 'தொடர்பு & புகார்கள்',
  legalPrivacy: 'சட்ட & தனியுரிமை',
  more: 'மேலும்',
  phoneTab: 'தொலைபேசி எண்',
  emailTab: 'மின்னஞ்சல்',
  verifyViaPhone: 'தொலைபேசி OTP மூலம் சரிபார்க்கவும்',
  verifyViaEmail: 'மின்னஞ்சல் OTP மூலம் சரிபார்க்கவும்',
  emailInput: 'மின்னஞ்சல் முகவரி:',
  aboutPageTitle: 'Matrix Investments PLC பற்றி',
  aboutPageDesc: 'நவீனம், நேர்மை மற்றும் உள்ளடக்கம் மூலம் இலங்கையின் மிகவும் நம்பகமான டிஜிட்டல் வரி உள்கட்டமைப்பை உருவாக்குதல்.',
  aboutPageMission: 'எங்கள் நோக்கம்',
  aboutPageMissionDesc: 'ஒவ்வொரு இலங்கை வரி செலுத்துவோருக்கும் அணுகக்கூடிய, துல்லியமான மற்றும் மலிவான டிஜிட்டல் வரி சேவைகளை வழங்குதல் — தொழில்நுட்பம் மூலம் கைமுறை தாக்கல் சுமையை நீக்குதல்.',
  aboutPageVision: 'எங்கள் பார்வை',
  aboutPageVisionDesc: '2030ல் AI வழிகாட்டல் மற்றும் ஒருங்கிணைந்த அரசு API அணுகல் மூலம் 20 லட்சத்திற்கும் மேலான வரி செலுத்துவோரை வலுப்படுத்தி தென் ஆசியாவின் முன்னணி டிஜிட்டல் வரி தளமாக மாறுதல்.',
  aboutMatrixDesc1: 'Matrix Investments PLC என்பது இலங்கை வரி செலுத்துவோருக்கும் உள்நாட்டு வருவாய் திணைக்களத்திற்கும் இடையிலான இடைவெளியை நிரப்ப நிறுவப்பட்ட நிதித் தொழில்நுட்ப நிறுவனம்.',
  aboutMatrixDesc2: 'எங்கள் குழு டிஜிட்டல் தளங்கள், தேசிய வரி கண்டிகள், நிதி ஆலோசனை மற்றும் இணக்க மேலாண்மை வழியாக செயல்படுகிறது.',
  groupPageTitle: 'எங்கள் குழு நிறுவனங்கள்',
  groupPageDesc: 'Matrix Investments PLC இலங்கையில் வரி, நிதி மற்றும் தொழில்நுட்ப சேவைகளில் தேர்ச்சி பெற்ற ஆறு சிறப்பு துணை நிறுவனங்கள் மூலம் செயல்படுகிறது.',
  investorPageTitle: 'முதலீட்டாளர் தொடர்பு',
  investorPageDesc: 'Matrix Investments PLC வெளிப்படைத்தன்மை, நிலையான வளர்ச்சி மற்றும் அனைத்து பங்குதாரர்களுக்கும் மதிப்பை வழங்குவதில் கடமைப்பட்டுள்ளது.',
  whyInvest: 'Matrix இல் முதலீடு ஏன்',
  investorContact: 'முதலீட்டாளர் விசாரணைகளுக்கு: investors@matrix.lk',
  careersPageTitle: 'Matrix இல் வாழ்க்கை வாய்ப்புகள்',
  careersPageDesc: 'இலங்கையின் வேகமாக வளரும் டிஜிட்டல் வரி தளத்தில் சேரவும். மில்லியன் கணக்கான இலங்கையர்களின் வரி மேலாண்மையை மாற்ற உதவ ஆர்வமுள்ளவர்களை தேடுகிறோம்.',
  openPositions: 'தற்போதைய வாய்ப்புகள்',
  applyNow: 'இப்போது விண்ணப்பிக்கவும்',
  noOpenings: 'தற்போது வாய்ப்புகள் இல்லை. careers@matrix.lk க்கு CV அனுப்பவும்.',
  whyUs: 'எங்களுடன் ஏன் பணிபுரிவது',
  contactPageTitle: 'தொடர்பு & புகார்கள்',
  contactPageDesc: 'உங்கள் கருத்தை நாங்கள் மதிக்கிறோம். கீழேயுள்ள எந்த சேனல் மூலமும் தொடர்புகொள்ளுங்கள்.',
  contactFormName: 'முழு பெயர்',
  contactFormEmail: 'மின்னஞ்சல்',
  contactFormPhone: 'தொலைபேசி எண்',
  contactFormSubject: 'விஷயம்',
  contactFormMessage: 'உங்கள் செய்தி',
  submitBtn: 'சமர்பிக்கவும்',
  complaintSection: 'புகார் தாக்கல் செய்யுங்கள்',
  getInTouch: 'தொடர்பு கொள்ளுங்கள்',
  thankYouContact: 'நன்றி! 24 மணி நேரத்தில் பதிலளிப்போம்.',
  legalPageTitle: 'சட்ட & தனியுரிமை',
  legalPageDesc: 'Matrix Investments PLC இலங்கை PDPA க்கு இணங்க உங்கள் தனிப்பட்ட தரவை பாதுகாக்க கடமைப்பட்டுள்ளது.',
  pdpaTitle: 'PDPA இணக்கம்',
  pdpaDesc: 'இலங்கை தனிப்பட்ட தரவு பாதுகாப்பு சட்டம் எண். 9 (2022) க்கு ஏற்ப, உங்கள் தரவு உங்கள் வெளிப்படையான ஒப்புதலுடன் மட்டுமே சேகரிக்கப்படுகிறது.',
  privacyPolicyFull: 'தனியுரிமைக் கொள்கை',
  termsOfServiceFull: 'சேவை விதிமுறைகள்',
  dataProtection: 'தரவு பாதுகாப்பு',
  consentFramework: 'ஒப்புதல் கட்டமைப்பு',
  dataRetention: 'தரவு தேக்கம்',
  yourRights: 'உங்கள் உரிமைகள்',
  servicesPageTitle: 'எங்கள் சேவைகள்',
  servicesPageDesc: 'இலங்கை முழுவதும் தனிநபர்கள் மற்றும் வணிகங்களுக்கான விரிவான வரி மற்றும் நிதி சேவைகள்.',
  individualTaxFiling: 'தனிப்பட்ட வரி தாக்கல்',
  individualTaxDesc: 'வேலைசெய்பவர்கள், சுயதொழில் மற்றும் தொழில் வல்லுநர்களுக்கான வருமான வரி தாக்கல்.',
  businessTaxFiling: 'வணிக வரி தாக்கல்',
  businessTaxDesc: 'அனைத்து அளவு வணிகங்களுக்கான நிறுவன வருமான வரி மற்றும் VAT தாக்கல்.',
  tinRegistration: 'TIN பதிவு',
  tinRegistrationDesc: 'TIN விண்ணப்பம் மற்றும் பதிவு சேவை. உள்நாட்டு வருவாய் திணைக்களத்துடன் முழு செயல்முறை வழிகாட்டல்.',
  complianceMonitoring: 'இணக்க கண்காணிப்பு',
  complianceMonitoringDesc: 'உங்கள் வரி கடமைகள், தவணை தேதிகள், அபராத குறிகள் மற்றும் ஆபத்து குறிகாட்டிகளை தொடர்ச்சியான கண்காணிப்பு.',
  guidePageTitle: 'வழிகாட்டி & வளங்கள்',
  guidePageDesc: 'உங்கள் வரி கடமைகளை புரிந்துகொள்ள மற்றும் தளத்தை பயனுள்ள முறையில் பயன்படுத்த இலவச கல்வி வளங்கள்.',
  guideUseOfTaxServices: 'வரி சேவைகளின் பயன்பாடு',
  guideUserGuide: 'பயனர் வழிகாட்டி',
  guideAgentGuide: 'ஏஜெண்ட் வழிகாட்டி',
  guideAboutUs: 'எங்களை பற்றி',
  guideHelpAI: 'AI உதவி பயிற்றுவிப்பாளர்',
  guideTaxCalendar: 'வரி நாட்காட்டி',
  freeOfCharge: 'இலவசம்',
  watchNow: 'இப்போது பாருங்கள்',
  comingSoon: 'விரைவில்',

  // ── General UI ────────────────────────────────────────────
  paid: 'கட்டண',
  free: 'இலவசம்',
  guideNote: 'முழு வழிகாட்டி உள்ளடக்கம் விரைவில்',
  subsidiaryServices: 'துணை சேவைகள்',
  groupStructure: 'குழு கட்டமைப்பு',
  groupStructureNote: 'அனைத்து துணை நிறுவனங்களும் Matrix Investments PLC இன் மூலோபாய வழிகாட்டலின் கீழ் செயல்படுகின்றன.',
  partnerWithUs: 'எங்களுடன் கூட்டாளராக இருங்கள்',
  partnerWithUsDesc: 'டிஜிட்டல் வரி மாற்றத்திற்கான எங்கள் நோக்கத்துடன் இணைந்த மூலோபாய முதலீட்டாளர்கள் மற்றும் கூட்டாளர்களை நாங்கள் வரவேற்கிறோம்.',
  dontSeeRole: "உங்கள் பங்கு தெரியவில்லையா?",
  dontSeeRoleDesc: "உங்கள் CV ஐ எங்கள் HR குழுவிற்கு அனுப்பவும்.",
  sendAnother: 'இன்னொன்றை அனுப்பு',
  sending: 'அனுப்பப்படுகிறது...',
  reviewAndRespond: 'எங்கள் குழு உங்கள் செய்தியை மதிப்பாய்வு செய்து விரைவில் பதிலளிக்கும்.',
  taxFilingComplianceTitle: 'வரி தாக்கல் மற்றும் இணக்கம்',
  myTaxDigitalServices: 'MyTax டிஜிட்டல் சேவைகள்',
  readyToFile: 'உங்கள் வரிகளை தாக்கல் செய்ய தயாரா?',
  readyToFileDesc: 'சில நிமிடங்களில் உங்கள் கணக்கை உருவாக்கி வரி இணக்கத்தை எங்களிடம் விட்டு விடுங்கள்.',
  investmentCase: 'முதலீட்டு வாய்ப்பு',
  cultureBenefits: 'கலாச்சாரம் மற்றும் நன்மைகள்',
  currentOpenings: 'தற்போதைய காலியிடங்கள்',
  coreServices: 'முக்கிய சேவைகள்',
  platformModules: 'தளம் தொகுதிகள்',
  videoGuidesTitle: 'வரி எளிய வழிகாட்டி வீடியோக்கள்',
  smsAlertsTitle: 'குறுஞ்செய்தி விழிப்பூட்டல்கள்',
  smsAlertsDesc: 'உங்கள் வரி பயணத்தின் ஒவ்வொரு படிநிலைக்கும் தானியங்கி குறுஞ்செய்தி அறிவிப்புகளுடன் தொடர்ந்து அறியவும்:',
  businessModelTitle: 'வணிக மாதிரி கண்ணோட்டம்',

  // ── About page stats ─────────────────────────────────────
  statsClients: 'வாடிக்கையாளர்கள்',
  statsYears: 'ஆண்டுகள் அனுபவம்',
  statsTaxReturns: 'வரி வருமானங்கள் தாக்கல் செய்யப்பட்டுள்ளன',
  statsDistricts: 'உள்ளடக்கிய மாவட்டங்கள்',

  // ── S&C service categories ────────────────────────────────
  scAccounts: 'கணக்குகள்',
  scProposals: 'முன்மொழிவுகள்',
  scInventory: 'சரக்கு மேலாண்மை',
  scTaxCategory: 'வரி',
  scCompanyReg: 'நிறுவன பதிவுகள்',
  scSecretarial: 'நிறுவனத்தின் செயலகப் பணிகள்',
  scRealEstate: 'ரியல் எஸ்டேட்',
  scMonthlyFinance: 'மாதாந்திர நிதி கண்காணிப்பு',
  scMonthlyAccounts: 'மாதாந்திர கணக்குகள்',
  scProfitReports: 'வணிக லாப அறிக்கைகள்',
  scLoanAccounts: 'கடன் நோக்கக் கணக்குகள்',
  scAnnualAccounts: 'ஆண்டு கணக்குகள்',
  scLoanProposal: 'கடன் முன்மொழிவு',
  scBusinessProposal: 'வணிக முன்மொழிவு',
  scStockVerification: 'பங்கு சரிபார்ப்பு',
  scDigitalStock: 'டிஜிட்டல் பார் பங்கு எண்ணிக்கைகள்',
  scIncomeTaxFiling: 'வருமான வரி தாக்கல்',
  scIncomeTaxReg: 'வருமான வரி பதிவு',
  scVatConsult: 'VAT ஆலோசனைகள்',
  scTaxConsult: 'வரி ஆலோசனைகள்',
  scBusinessReg: 'வணிக பதிவு',
  scCharityReg: 'தொண்டு பதிவு',
  scAnnualReturn: 'ஆண்டு வருவாய் தாக்கல்',
  scSecretary: 'செயலாளர் சேவைகள்',
  scDealAdvisory: 'ஒப்பந்த ஆலோசனை',

  // ── Digital tools ─────────────────────────────────────────
  toolMyTaxApp: 'MyTax டிஜிட்டல் ஆப்',
  toolGuidanceVideos: 'வரி எளிய வழிகாட்டி வீடியோக்கள்',
  toolUserGuideLabel: 'பயனர் வழிகாட்டி',
  toolAIInstructor: 'AI வரி பயிற்றுவிப்பாளர்',
  toolTaxCalendar: 'வரி நாட்காட்டி',
  toolAgentGuide: 'ஏஜென்ட் வழிகாட்டி',

  // ── Group Companies ───────────────────────────────────────
  company1Tagline: 'வணிகம் மற்றும் வரி ஆலோசனை சிறப்பு',
  company1Desc: 'இலங்கை முழுவதும் உள்ள வணிகங்கள் மற்றும் தனிநபர்களுக்கு விரிவான கணக்கியல், வரி, நிறுவனப் பதிவு சேவைகள்.',
  company2Tagline: 'டிஜிட்டல் வரி கண்டுபிடிப்பு',
  company2Desc: 'Matrix Investments PLC இன் தொழில்நுட்ப பிரிவு, வரி தாக்கல் மற்றும் இணக்க மேலாண்மைக்கான MyTax டிஜிட்டல் தளத்தை இயக்குகிறது.',
  company3Tagline: 'தேசிய வரி அணுகல் புள்ளிகள்',
  company3Desc: 'Matrix Tax Booth தேசிய வெளியீட்டை நிர்வகிக்கிறது.',
  company4Tagline: 'முதலீடு மற்றும் நிதி ஆலோசனை',
  company4Desc: 'கார்ப்பரேட் மற்றும் தனிப்பட்ட வாடிக்கையாளர்களுக்கு நிபுணர் நிதி ஆலோசனை மற்றும் முதலீட்டு திட்டமிடலை வழங்குதல்.',
  company5Tagline: 'ஒழுங்குமுறை இணக்க மேலாண்மை',
  company5Desc: 'ஒழுங்குமுறை இணக்க கண்காணிப்பு மற்றும் அரசாங்க தொடர்பு சேவைகளில் நிபுணத்துவம் பெற்றது.',
  company6Tagline: 'வரிக்கான தரவு நுண்ணறிவு',
  company6Desc: 'வாடிக்கையாளர் தரவுத்தள மேலாண்மை மற்றும் AI அடிப்படையிலான வரி கேள்வித்தாள் அமைப்புகளை ஆதரிக்கும் தரவு பகுப்பாய்வு.',
  svcAccounts: 'கணக்குகள்',
  svcTaxFiling: 'வரி தாக்கல்',
  svcCompanyReg: 'நிறுவன பதிவுகள்',
  svcInventoryMgmt: 'சரக்கு மேலாண்மை',
  svcRealEstate: 'ரியல் எஸ்டேட்',
  svcProposals: 'முன்மொழிவுகள்',
  svcSecretarialWorks: 'செயலகப் பணிகள்',
  svcMyTaxApp: 'MyTax ஆப்',
  svcDigitalTaxFiling: 'டிஜிட்டல் வரி தாக்கல்',
  svcTINServices: 'TIN சேவைகள்',
  svcComplianceTools: 'இணக்க கருவிகள்',
  svcAIAssistant: 'AI வரி உதவியாளர்',
  svcTINRegistration: 'TIN பதிவு',
  svcAppOnboarding: 'ஆப் ஆன்போர்டிங்',
  svcVoiceFiling: 'குரல் தாக்கல்',
  svcPaymentGuidance: 'கட்டண வழிகாட்டுதல்',
  svcFinancialAdvisory: 'நிதி ஆலோசனை',
  svcInvestmentPlanning: 'முதலீட்டு திட்டமிடல்',
  svcCapitalManagement: 'மூலதன மேலாண்மை',
  svcRiskAssessment: 'ஆபத்து மதிப்பீடு',
  svcComplianceAudits: 'இணக்க தணிக்கைகள்',
  svcRiskManagement: 'ஆபத்து மேலாண்மை',
  svcGovernmentLiaison: 'அரசாங்க தொடர்பு',
  svcRegulatoryReporting: 'ஒழுங்குமுறை அறிக்கை',
  svcDataAnalytics: 'தரவு பகுப்பாய்வு',
  svcClientDatabase: 'வாடிக்கையாளர் தரவுத்தள மேலாண்மை',
  svcReportingTools: 'அறிக்கை கருவிகள்',

  // ── Investor Relations ────────────────────────────────────
  whyGrowingMarket: 'வளரும் சந்தை',
  whyGrowingMarketDesc: 'இலங்கையில் 10+ மில்லியன் வரிக்குட்பட்ட நபர்கள் உள்ளனர். 30% இற்கும் குறைவானவர்களே தற்போது வருமானத்தை தாக்கல் செய்கின்றனர்.',
  whyRegulatoryTailwind: 'ஒழுங்குமுறை பின்னணி',
  whyRegulatoryTailwindDesc: 'டிஜிட்டல் வரி சமர்ப்பிப்பு மற்றும் TIN பதிவுக்கான அரசாங்க அறிவுறுத்தல்கள் டிஜிட்டல் தளங்களை வேகமாக ஏற்றுக்கொள்வதற்கு உந்துகின்றன.',
  whyTechMoat: 'தொழில்நுட்ப தடைகள்',
  whyTechMoatDesc: 'AI வரி கேள்வித்தாள், பன்மொழி குரல் இடைமுகம் மற்றும் தேசிய சாவடி நெட்வொர்க் வலுவான போட்டி தடைகளை உருவாக்குகின்றன.',
  whyGovPartnership: 'அரசாங்க கூட்டு',
  whyGovPartnershipDesc: 'தரவு அணுகல் API கள் மற்றும் தேசிய வரி சாவடிகளுக்கான IRD உடனான மூலோபாய கூட்டு.',
  whyRegionalExpansion: 'பிராந்திய விரிவாக்கம்',
  whyRegionalExpansionDesc: 'இதே போன்ற வரி இணக்க சவால்களுடன் பிற தெற்காசிய சந்தைகளுக்கான விரிவாக்கத்தை தளம் ஆதரிக்கிறது.',
  whyDiversifiedRevenue: 'பன்முகப்படுத்தப்பட்ட வருவாய்',
  whyDiversifiedRevenueDesc: 'SaaS சந்தாக்கள், தாக்கல் கட்டணங்கள், சாவடி உரிமையாளர் மாதிரி மற்றும் ஆலோசனை சேவைகளில் இருந்து வருவாய்.',
  bmClientSubs: 'வாடிக்கையாளர் சந்தாக்கள்',
  bmClientSubsDesc: 'தனிநபர்கள் மற்றும் வணிகங்களுக்கான வருடாந்திர வரி மேலாண்மை தொகுப்புகள்',
  bmPerFiling: 'தாக்கல் கட்டணங்கள்',
  bmPerFilingDesc: 'தாக்கல் செய்யப்பட்ட ஒவ்வொரு வரி வருமானத்திற்கும் பரிவர்த்தனை அடிப்படையிலான வருவாய்',
  bmBoothFranchise: 'வரி சாவடி உரிமையாளர்',
  bmBoothFranchiseDesc: 'தேசிய வரி சாவடி நெட்வொர்க் ஆபரேட்டர்களிடமிருந்து உரிமையாளர் கட்டணம்',
  bmAdvisory: 'ஆலோசனை சேவைகள்',
  bmAdvisoryDesc: 'S&C Business Consultants மூலம் பிரீமியம் ஆலோசனை',
  bmGovAPI: 'அரசாங்க API அணுகல்',
  bmGovAPIDesc: 'எதிர்காலம்: அரசாங்க உரிமம் பெற்ற தரவு சேவைகள்',
  invStatRevenue: 'வருவாய் பைப்லைன்',
  invStatCompanies: 'துணை நிறுவனங்கள்',
  invStatDistricts: 'மாவட்ட கவரேஜ்',
  invStatTarget: 'இலக்கு: 2M வாடிக்கையாளர்கள்',

  // ── Careers ───────────────────────────────────────────────
  whyJobCuttingEdge: 'அதிநவீன தொழில்நுட்பம்',
  whyJobCuttingEdgeDesc: 'மில்லியன் கணக்கானவர்களுக்கு சேவை செய்யும் AI, குரல் அங்கீகாரம் மற்றும் பன்மொழி மொபைல் ஆப்ஸில் வேலை செய்யுங்கள்.',
  whyJobNationalImpact: 'தேசிய தாக்கம்',
  whyJobNationalImpactDesc: 'இலங்கை குடிமக்கள் மற்றும் வணிகங்களின் வரி இணக்கத்தை நேரடியாக மேம்படுத்துங்கள்.',
  whyJobLearning: 'கற்றல் கலாச்சாரம்',
  whyJobLearningDesc: 'வழக்கமான பயிற்சி, வழிகாட்டல் திட்டங்கள் மற்றும் தொழில்முறை சான்றிதழ்களுக்கான அணுகல்.',
  whyJobGrowth: 'வளர்ச்சி வாய்ப்புகள்',
  whyJobGrowthDesc: 'தொழில்நுட்பம், ஆலோசனை மற்றும் செயல்பாடுகள் முழுவதும் தெளிவான தொழில் பாதைகளைக் கொண்ட வேகமாக வளரும் நிறுவனம்.',
  jobFullTime: 'முழு நேரம்',
  jobContract: 'ஒப்பந்தம்',
  jobColomboPH: 'கொழும்பு',
  jobMultiLoc: 'பல இடங்கள்',
  jobIslandWide: 'தீவு முழுவதும்',
  jobTechDept: 'தொழில்நுட்பம்',
  jobAdvisoryDept: 'ஆலோசனை',
  jobOpsDept: 'செயல்பாடுகள்',
  jobReactTitle: 'React / TypeScript டெவலப்பர்',
  jobReactDesc: 'React, TypeScript மற்றும் நவீன APIகளைப் பயன்படுத்தி MyTax வலைத் தளத்தை உருவாக்கி பராமரிக்கவும்.',
  jobFlutterTitle: 'Flutter மொபைல் டெவலப்பர்',
  jobFlutterDesc: 'iOS மற்றும் Android க்கான MyTax மொபைல் ஆப்ஸை உருவாக்கி மேம்படுத்தவும்.',
  jobTaxConsultTitle: 'வரி ஆலோசகர்',
  jobTaxConsultDesc: 'வருமான வரி தாக்கல், TIN பதிவு மற்றும் இணக்க ஆலோசனை ஆகியவற்றில் வாடிக்கையாளர்களுக்கு உதவுங்கள்.',
  jobBoothTitle: 'வரி சாவடி அதிகாரி',
  jobBoothDesc: 'GS பிரிவுகளில் Matrix வரி சாவடிகளை இயக்கவும்.',
  jobDataTitle: 'தரவு பகுப்பாய்வாளர்',
  jobDataDesc: 'சேவை விநியோகத்தை மேம்படுத்த மற்றும் இணக்க அபாய டாஷ்போர்டுகளை உருவாக்க வாடிக்கையாளர் தரவை பகுப்பாய்வு செய்யுங்கள்.',
  jobSupportTitle: 'வாடிக்கையாளர் ஆதரவு அதிகாரி',
  jobSupportDesc: 'ஆங்கிலம், சிங்களம் மற்றும் தமிழில் தொலைபேசி, மின்னஞ்சல் மற்றும் WhatsApp மூலம் வாடிக்கையாளர் வினவல்களைக் கையாளவும்.',

  // ── Contact page ──────────────────────────────────────────
  contactEmailLabel: 'மின்னஞ்சல்',
  contactHotlineLabel: 'ஹாட்லைன்',
  contactLocationLabel: 'இடம்',
  contactHoursLabel: 'வணிக நேரங்கள்',
  contactWhatsAppLabel: 'WhatsApp',
  contactWebLabel: 'இணையம்',
  contactLocationValue: 'கொழும்பு, இலங்கை',
  contactBusinessHoursValue: 'திங்கள்-வெள்ளி: காலை 8:30 - மாலை 5:00',
  responseCommitment1: 'அனைத்து வினவல்களுக்கும் 24 வணிக மணிநேரத்திற்குள் பதிலளிக்கப்படும்.',
  responseCommitment2: 'புகார்கள் 48 மணி நேரத்திற்குள் மூத்த அதிகாரிக்கு அனுப்பப்படும்.',
  complaintFormDesc: 'எங்கள் சேவைகள், அதிகாரிகள் அல்லது தளம் தொடர்பான முறையான புகார்களுக்கு, "புகார்" என்ற விஷயத்துடன் மேலே உள்ள படிவத்தைப் பயன்படுத்தவும்.',
  complaintPdpaNote: 'அனைத்து புகார்களும் ரகசியமாக மற்றும் எங்கள் PDPA இணக்கமான தரவு கையாளுதல் கொள்கைக்கு ஏற்ப கையாளப்படுகின்றன.',
  phFullName: 'உங்கள் முழு பெயர்',
  phEmail: 'நீங்கள்@உதாரணம்.com',
  phPhone: '+94 XX XXX XXXX',
  phSubject: 'உங்கள் விசாரணையின் பொருள்',
  phMessage: 'உங்கள் செய்தியை இங்கே எழுதவும்...',

  // ── Legal content ─────────────────────────────────────────
  pdpaBadgeTitle: 'PDPA இணக்கமானது - 2022 ஆம் ஆண்டின் 9 ஆம் இலக்க தனிப்பட்ட தரவு பாதுகாப்பு சட்டம்',
  pdpaBadgeDesc: "இலங்கையின் தனிப்பட்ட தரவு பாதுகாப்புச் சட்டத்திற்கு முழுமையாக இணங்க Matrix Investments PLC உறுதிபூண்டுள்ளது.",
  legalLastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது: ஜனவரி 2026',
  legalPdpa1: '2022 ஆம் ஆண்டின் 9 ஆம் இலக்க தனிப்பட்ட தரவு பாதுகாப்புச் சட்டத்திற்கு (இலங்கை) நாங்கள் முழுமையாக இணங்குகிறோம்.',
  legalPdpa2: 'உங்கள் வெளிப்படையான ஒப்புதலுடன் மட்டுமே உங்கள் தரவு சேகரிக்கப்படுகிறது.',
  legalPdpa3: 'அங்கீகரிக்கப்படாத அணுகல், இழப்பு அல்லது மாற்றத்திற்கு எதிராக உங்கள் தரவைப் பாதுகாக்க தொழில்நுட்ப மற்றும் நிறுவன நடவடிக்கைகளை நாங்கள் செயல்படுத்துகிறோம்.',
  legalPdpa4: 'எந்த நேரத்திலும் உங்கள் ஒப்புதலை நீங்கள் திரும்பப் பெறலாம்.',
  legalPriv1: 'நாங்கள் சேகரிக்கிறோம்: NIC எண், மொபைல் எண், மின்னஞ்சல் முகவரி, முழு பெயர், இருப்பிடத் தரவு மற்றும் வரி தொடர்பான நிதித் தகவல்கள்.',
  legalPriv2: 'சட்டத்தால் தேவைப்படும் இடங்களைத் தவிர, உங்கள் அனுமதியின்றி நாங்கள் உங்கள் தனிப்பட்ட தரவை மூன்றாம் தரப்பினருடன் விற்கவோ, வாடகைக்கு விடவோ அல்லது பகிரவோ மாட்டோம்.',
  legalPriv3: 'வழக்கமான காப்புப்பிரதிகளுடன் குறியாக்கம் செய்யப்பட்ட சேவையகங்களில் தரவு சேமிக்கப்படுகிறது.',
  legalPriv4: 'குக்கீகள் அமர்வு நிர்வாகத்திற்கு மட்டுமே பயன்படுத்தப்படுகின்றன.',
  legalTerms1: 'MyTax ஐப் பயன்படுத்துவதன் மூலம், வரி தாக்கல் நோக்கங்களுக்காக துல்லியமான மற்றும் உண்மையான தகவல்களை வழங்க நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',
  legalTerms2: 'பயனர்களால் வழங்கப்பட்ட தவறான தகவல்களால் ஏற்படும் வரி அபராதங்களுக்கு Matrix Investments PLC பொறுப்பல்ல.',
  legalTerms3: 'தளத்தின் அங்கீகரிக்கப்படாத பயன்பாடு அல்லது தவறான பயன்பாடு கணக்கு நிறுத்தப்படுவதற்கு வழிவகுக்கும்.',
  legalTerms4: '"கட்டண" எனக் குறிக்கப்பட்ட சேவைகள் பொருந்தக்கூடிய கட்டணங்களுக்கு உட்பட்டவை.',
  legalData1: 'அனைத்து தரவு பரிமாற்றங்களும் TLS 1.2+ ஐப் பயன்படுத்தி குறியாக்கம் செய்யப்பட்டுள்ளன.',
  legalData2: 'கடவுச்சொற்கள் ஹாஷ் செய்யப்பட்டுள்ளன மற்றும் சாதாரண உரையில் சேமிக்கப்படுவதில்லை.',
  legalData3: 'அனைத்து கணக்கு அணுகலுக்கும் இரு காரணி அங்கீகாரம் (OTP) தேவை.',
  legalData4: 'வழக்கமான பாதுகாப்பு தணிக்கைகள் செய்யப்படுகின்றன.',
  legalConsent1: 'பதிவு செய்யும் போது, தரவு சேகரிப்பு மற்றும் செயலாக்கத்திற்கு பயனர்கள் வெளிப்படையான ஒப்புதல் அளிக்கிறார்கள்.',
  legalConsent2: 'ஒப்புதல் பதிவு செய்யப்பட்டுள்ளது.',
  legalConsent3: 'கணக்கு அமைப்புகள் மூலம் பயனர்கள் எந்த நேரத்திலும் தங்கள் ஒப்புதலைப் பார்க்கலாம், புதுப்பிக்கலாம் அல்லது திரும்பப் பெறலாம்.',
  legalConsent4: 'அனைத்து ஒப்புதல் பதிவுகளும் எங்கள் தணிக்கை பதிவில் பராமரிக்கப்படுகின்றன.',
  legalRet1: 'வாடிக்கையாளர் உறவின் காலத்திற்கு செயலில் உள்ள கணக்குத் தரவு தக்கவைக்கப்படுகிறது.',
  legalRet2: 'வரி தாக்கல் பதிவுகள் குறைந்தபட்சம் 5 ஆண்டுகளுக்கு தக்கவைக்கப்படுகின்றன.',
  legalRet3: 'நீக்கப்பட்ட கணக்குத் தரவு 30 நாட்களுக்குள் கணினிகளிலிருந்து நீக்கப்படும்.',
  legalRet4: 'காப்பு பிரதிகள் 90 நாட்களுக்குள் நீக்கப்படும்.',
  legalRight1: 'அணுகுவதற்கான உரிமை: உங்களைப் பற்றி நாங்கள் வைத்திருக்கும் அனைத்து தரவுகளின் நகலையும் கோருங்கள்.',
  legalRight2: 'திருத்துவதற்கான உரிமை: உங்கள் சுயவிவரத்தில் உள்ள ஏதேனும் தவறான தகவலை சரிசெய்யவும்.',
  legalRight3: 'அழிப்பதற்கான உரிமை: உங்கள் கணக்கு மற்றும் தொடர்புடைய தரவை நீக்குமாறு கோருங்கள்.',
  legalRight4: 'தரவு பெயர்வுத்திறனுக்கான உரிமை: இயந்திரம் படிக்கக்கூடிய வடிவத்தில் உங்கள் தரவை ஏற்றுமதி செய்யுங்கள்.',
  legalRight5: 'இலங்கையின் தரவு பாதுகாப்பு அதிகாரசபையிடம் புகார்களை பதிவு செய்யுங்கள்.',

  // ── Services page ─────────────────────────────────────────
  tagIndividuals: 'தனிநபர்கள்',
  tagBusinesses: 'வணிகங்கள்',
  tagRegistration: 'பதிவு',
  tagMonitoring: 'கண்காணிப்பு',
  tagPrimary: 'முதன்மை',
  platM1Label: 'வரி கோப்பு சமர்ப்பணம்',
  platM2Label: 'TIN எண் நிலை',
  platM3Label: 'வரி கணக்கீட்டி',
  platM5Label: 'இறுதி வரி கணக்கீடு',
  platM6Label: 'TIN சான்றிதழ் கோரிக்கை',
  platM7Label: 'TIN சான்றிதழ் விண்ணப்பம்',
  platM8Label: 'வரி செலுத்துவோர் தகவல் புதுப்பிப்பு',
  platM9Label: 'வரி நிர்வாக ஆதரவு',

  // ── Guide page ────────────────────────────────────────────
  guideUseOfTaxDesc: 'TIN பதிவு முதல் ஆண்டு வரி தாக்கல் வரை அனைத்து MyTax டிஜிட்டல் சேவைகளையும் எவ்வாறு திறம்பட பயன்படுத்துவது என்பதை அறிக.',
  guideUserGuideDesc: 'MyTax தளத்திற்குச் செல்லவும், அவர்களின் தாக்கல்களை முடிக்கவும் தனிப்பட்ட வரி செலுத்துவோருக்கான படிப்படியான வழிகாட்டி.',
  guideAgentGuideDesc: 'வாடிக்கையாளர் இலாகாக்கள் மற்றும் பணிகளை நிர்வகிப்பது குறித்த வரி முகவர்கள் மற்றும் அதிகாரிகளுக்கான விரிவான வழிகாட்டி.',
  guideAboutUsDesc: 'Matrix Investments PLC, எங்கள் பணி, துணை நிறுவனங்கள் மற்றும் இலங்கை முழுவதும் நாங்கள் வழங்கும் சேவைகள் பற்றி அறிக.',
  guideHelpAIDesc: 'சிங்களம், தமிழ் அல்லது ஆங்கிலத்தில் எங்களது AI-இயங்கும் வரி பயிற்றுவிப்பாளருடன் உரையாடுங்கள்.',
  guideTaxCalendarDesc: 'இலங்கைக்கான முக்கியமான வரி காலக்கெடு, தாக்கல் செய்ய வேண்டிய தேதிகள், கட்டண அட்டவணைகள் மற்றும் அபராதம் தவிர்ப்பு காலவரிசை.',
  smsRegTag: 'பதிவு',
  smsRegText: 'பதிவு செய்தவுடன் வாடிக்கையாளர் ஐடி உறுதிப்படுத்தல்',
  smsAssignTag: 'பணி ஒதுக்கீடு',
  smsAssignText: 'உங்கள் பணி ஒரு அதிகாரிக்கு ஒதுக்கப்படும் போது',
  smsDocsTag: 'ஆவணங்கள்',
  smsDocsText: 'நிலுவையில் உள்ள அல்லது விடுபட்ட ஆவணங்களுக்கான விழிப்பூட்டல்கள்',
  smsDoneTag: 'முடிந்தது',
  smsDoneText: 'உங்கள் வரி வேலை முடிந்ததும் அறிவிப்பு',
  smsInvoiceTag: 'விலைப்பட்டியல்',
  smsInvoiceText: 'நிலுவைத் தேதியுடன் விலைப்பட்டியல் உருவாக்கப்பட்டது',
  smsConfirmedTag: 'உறுதிப்படுத்தப்பட்டது',
  smsConfirmedText: 'குறிப்பு எண்ணுடன் வரி வருமான தாக்கல் உறுதிப்படுத்தல்',
};

export function getStrings(language: Language): Record<string, string> {
  switch (language) {
    case 'TAMIL':
      return tamil;
    case 'SINHALA':
      return sinhala;
    default:
      return english;
  }
}
